const { test } = require("@jest/globals");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const w = require(process.env.WEB_IFC_API || "../../dist/web-ifc-api-node.js");
const base = fs.readFileSync(new URL("./fixtures/binary/strings-base.ifc", require("node:url").pathToFileURL(__filename).href), "utf8");
for (const schema of ["IFC4", "IFC4X3_ADD2"]) test("binary pixel parse/write/save " + schema, async () => {
  const api = new w.IfcAPI();
  await api.Init();
  const text = base.replace("FILE_SCHEMA(('IFC4'))", `FILE_SCHEMA(('${schema}'))`).replace("ENDSEC;\nEND-ISO", '#9000=IFCPIXELTEXTURE(.T.,.T.,$,$,$,1,1,3,("0FF00AA"));\nENDSEC;\nEND-ISO');
  let m = api.OpenModel(new TextEncoder().encode(text));
  const raw = api.GetRawLineData(m, 9e3);
  assert.equal(raw.arguments.length, 9);
  assert.equal(raw.arguments[8][0].type, 11);
  assert.equal(raw.arguments[8][0].value, "0FF00AA");
  const row = api.GetLine(m, 9e3);
  assert.equal(row.Pixel.length, 1);
  assert.equal(row.Pixel[0].value, "0FF00AA");
  row.Pixel[0].value = "0ABCDEF";
  api.WriteLine(m, row);
  assert.equal(api.GetLine(m, 9e3).Pixel[0].value, "0ABCDEF");
  const saved = api.SaveModel(m);
  api.CloseModel(m);
  assert.match(new TextDecoder().decode(saved), /"0ABCDEF"/);
  m = api.OpenModel(saved);
  assert.equal(api.GetLine(m, 9e3).Pixel[0].value, "0ABCDEF");
  api.CloseModel(m);
});
test("IFC2X3 primitive binary array remains binary when written", async () => {
  const api = new w.IfcAPI();
  await api.Init();
  const base2x3 = fs.readFileSync(new URL("./fixtures/binary/ifc2x3-block.ifc", require("node:url").pathToFileURL(__filename).href), "utf8");
  const text = base2x3.replace("ENDSEC;\nEND-ISO", '#9000=IFCPIXELTEXTURE(.T.,.T.,.TEXTURE.,$,1,1,3,("0FF00AA"));\nENDSEC;\nEND-ISO');
  let m = api.OpenModel(new TextEncoder().encode(text));
  const row = api.GetLine(m, 9e3);
  assert.deepEqual(row.Pixel, ["0FF00AA"]);
  row.Pixel[0] = "0ABCDEF";
  api.WriteLine(m, row);
  const saved = api.SaveModel(m);
  api.CloseModel(m);
  assert.match(new TextDecoder().decode(saved), /"0ABCDEF"/);
  m = api.OpenModel(saved);
  assert.deepEqual(api.GetLine(m, 9e3).Pixel, ["0ABCDEF"]);
  api.CloseModel(m);
});
