#include <unordered_set>
#include <string>
#include "ifc-schema.h"
#include "IfcSchemaManager.h"
namespace webifc::schema {
void IfcSchemaManager::initSchemaData() {
_ifcElements.insert(IFCPRODUCT);
_ifcElements.insert(IFCPROXY);
_ifcElements.insert(IFCSPATIALSTRUCTUREELEMENT);
_ifcElements.insert(IFCSTRUCTURALACTIVITY);
_ifcElements.insert(IFCSTRUCTURALITEM);
_ifcElements.insert(IFCSTRUCTURALMEMBER);
_ifcElements.insert(IFCSTRUCTURALREACTION);
_ifcElements.insert(IFCSTRUCTURALSURFACEMEMBER);
_ifcElements.insert(IFCSTRUCTURALSURFACEMEMBERVARYING);
_ifcElements.insert(IFCANNOTATION);
_ifcElements.insert(IFCBUILDING);
_ifcElements.insert(IFCBUILDINGSTOREY);
_ifcElements.insert(IFCELEMENT);
_ifcElements.insert(IFCELEMENTASSEMBLY);
_ifcElements.insert(IFCELEMENTCOMPONENT);
_ifcElements.insert(IFCEQUIPMENTELEMENT);
_ifcElements.insert(IFCFASTENER);
_ifcElements.insert(IFCFEATUREELEMENT);
_ifcElements.insert(IFCFEATUREELEMENTADDITION);
_ifcElements.insert(IFCFEATUREELEMENTSUBTRACTION);
_ifcElements.insert(IFCFURNISHINGELEMENT);
_ifcElements.insert(IFCGRID);
_ifcElements.insert(IFCMECHANICALFASTENER);
_ifcElements.insert(IFCOPENINGELEMENT);
_ifcElements.insert(IFCPORT);
_ifcElements.insert(IFCPROJECTIONELEMENT);
_ifcElements.insert(IFCSITE);
_ifcElements.insert(IFCSPACE);
_ifcElements.insert(IFCSTRUCTURALACTION);
_ifcElements.insert(IFCSTRUCTURALCONNECTION);
_ifcElements.insert(IFCSTRUCTURALCURVECONNECTION);
_ifcElements.insert(IFCSTRUCTURALCURVEMEMBER);
_ifcElements.insert(IFCSTRUCTURALCURVEMEMBERVARYING);
_ifcElements.insert(IFCSTRUCTURALLINEARACTION);
_ifcElements.insert(IFCSTRUCTURALLINEARACTIONVARYING);
_ifcElements.insert(IFCSTRUCTURALPLANARACTION);
_ifcElements.insert(IFCSTRUCTURALPLANARACTIONVARYING);
_ifcElements.insert(IFCSTRUCTURALPOINTACTION);
_ifcElements.insert(IFCSTRUCTURALPOINTCONNECTION);
_ifcElements.insert(IFCSTRUCTURALPOINTREACTION);
_ifcElements.insert(IFCSTRUCTURALSURFACECONNECTION);
_ifcElements.insert(IFCTRANSPORTELEMENT);
_ifcElements.insert(IFCVIRTUALELEMENT);
_ifcElements.insert(IFCBUILDINGELEMENT);
_ifcElements.insert(IFCBUILDINGELEMENTCOMPONENT);
_ifcElements.insert(IFCBUILDINGELEMENTPART);
_ifcElements.insert(IFCBUILDINGELEMENTPROXY);
_ifcElements.insert(IFCCOLUMN);
_ifcElements.insert(IFCCOVERING);
_ifcElements.insert(IFCCURTAINWALL);
_ifcElements.insert(IFCDISCRETEACCESSORY);
_ifcElements.insert(IFCDISTRIBUTIONELEMENT);
_ifcElements.insert(IFCDISTRIBUTIONFLOWELEMENT);
_ifcElements.insert(IFCDISTRIBUTIONPORT);
_ifcElements.insert(IFCDOOR);
_ifcElements.insert(IFCEDGEFEATURE);
_ifcElements.insert(IFCELECTRICALELEMENT);
_ifcElements.insert(IFCENERGYCONVERSIONDEVICE);
_ifcElements.insert(IFCFLOWCONTROLLER);
_ifcElements.insert(IFCFLOWFITTING);
_ifcElements.insert(IFCFLOWMOVINGDEVICE);
_ifcElements.insert(IFCFLOWSEGMENT);
_ifcElements.insert(IFCFLOWSTORAGEDEVICE);
_ifcElements.insert(IFCFLOWTERMINAL);
_ifcElements.insert(IFCFLOWTREATMENTDEVICE);
_ifcElements.insert(IFCFOOTING);
_ifcElements.insert(IFCMEMBER);
_ifcElements.insert(IFCPILE);
_ifcElements.insert(IFCPLATE);
_ifcElements.insert(IFCRAILING);
_ifcElements.insert(IFCRAMP);
_ifcElements.insert(IFCRAMPFLIGHT);
_ifcElements.insert(IFCREINFORCINGELEMENT);
_ifcElements.insert(IFCREINFORCINGMESH);
_ifcElements.insert(IFCROOF);
_ifcElements.insert(IFCROUNDEDEDGEFEATURE);
_ifcElements.insert(IFCSLAB);
_ifcElements.insert(IFCSTAIR);
_ifcElements.insert(IFCSTAIRFLIGHT);
_ifcElements.insert(IFCTENDON);
_ifcElements.insert(IFCTENDONANCHOR);
_ifcElements.insert(IFCWALL);
_ifcElements.insert(IFCWALLSTANDARDCASE);
_ifcElements.insert(IFCWINDOW);
_ifcElements.insert(IFCBEAM);
_ifcElements.insert(IFCCHAMFEREDGEFEATURE);
_ifcElements.insert(IFCDISTRIBUTIONCHAMBERELEMENT);
_ifcElements.insert(IFCDISTRIBUTIONCONTROLELEMENT);
_ifcElements.insert(IFCELECTRICDISTRIBUTIONPOINT);
_ifcElements.insert(IFCREINFORCINGBAR);
_ifcElements.insert(IFCSPATIALELEMENT);
_ifcElements.insert(IFCSPATIALZONE);
_ifcElements.insert(IFCSTRUCTURALSURFACEREACTION);
_ifcElements.insert(IFCEXTERNALSPATIALSTRUCTUREELEMENT);
_ifcElements.insert(IFCFURNITURE);
_ifcElements.insert(IFCGEOGRAPHICELEMENT);
_ifcElements.insert(IFCOPENINGSTANDARDCASE);
_ifcElements.insert(IFCSTRUCTURALCURVEACTION);
_ifcElements.insert(IFCSTRUCTURALCURVEREACTION);
_ifcElements.insert(IFCSTRUCTURALSURFACEACTION);
_ifcElements.insert(IFCSURFACEFEATURE);
_ifcElements.insert(IFCSYSTEMFURNITUREELEMENT);
_ifcElements.insert(IFCVIBRATIONISOLATOR);
_ifcElements.insert(IFCVOIDINGFEATURE);
_ifcElements.insert(IFCCHIMNEY);
_ifcElements.insert(IFCCIVILELEMENT);
_ifcElements.insert(IFCCOLUMNSTANDARDCASE);
_ifcElements.insert(IFCDOORSTANDARDCASE);
_ifcElements.insert(IFCENGINE);
_ifcElements.insert(IFCEVAPORATIVECOOLER);
_ifcElements.insert(IFCEVAPORATOR);
_ifcElements.insert(IFCEXTERNALSPATIALELEMENT);
_ifcElements.insert(IFCFLOWMETER);
_ifcElements.insert(IFCHEATEXCHANGER);
_ifcElements.insert(IFCHUMIDIFIER);
_ifcElements.insert(IFCINTERCEPTOR);
_ifcElements.insert(IFCJUNCTIONBOX);
_ifcElements.insert(IFCLAMP);
_ifcElements.insert(IFCLIGHTFIXTURE);
_ifcElements.insert(IFCMEDICALDEVICE);
_ifcElements.insert(IFCMEMBERSTANDARDCASE);
_ifcElements.insert(IFCMOTORCONNECTION);
_ifcElements.insert(IFCOUTLET);
_ifcElements.insert(IFCPIPEFITTING);
_ifcElements.insert(IFCPIPESEGMENT);
_ifcElements.insert(IFCPLATESTANDARDCASE);
_ifcElements.insert(IFCPROTECTIVEDEVICE);
_ifcElements.insert(IFCPUMP);
_ifcElements.insert(IFCSANITARYTERMINAL);
_ifcElements.insert(IFCSHADINGDEVICE);
_ifcElements.insert(IFCSLABELEMENTEDCASE);
_ifcElements.insert(IFCSLABSTANDARDCASE);
_ifcElements.insert(IFCSOLARDEVICE);
_ifcElements.insert(IFCSPACEHEATER);
_ifcElements.insert(IFCSTACKTERMINAL);
_ifcElements.insert(IFCSWITCHINGDEVICE);
_ifcElements.insert(IFCTANK);
_ifcElements.insert(IFCTRANSFORMER);
_ifcElements.insert(IFCTUBEBUNDLE);
_ifcElements.insert(IFCUNITARYEQUIPMENT);
_ifcElements.insert(IFCVALVE);
_ifcElements.insert(IFCWALLELEMENTEDCASE);
_ifcElements.insert(IFCWASTETERMINAL);
_ifcElements.insert(IFCWINDOWSTANDARDCASE);
_ifcElements.insert(IFCAIRTERMINAL);
_ifcElements.insert(IFCAIRTERMINALBOX);
_ifcElements.insert(IFCAIRTOAIRHEATRECOVERY);
_ifcElements.insert(IFCAUDIOVISUALAPPLIANCE);
_ifcElements.insert(IFCBEAMSTANDARDCASE);
_ifcElements.insert(IFCBOILER);
_ifcElements.insert(IFCBURNER);
_ifcElements.insert(IFCCABLECARRIERFITTING);
_ifcElements.insert(IFCCABLECARRIERSEGMENT);
_ifcElements.insert(IFCCABLEFITTING);
_ifcElements.insert(IFCCABLESEGMENT);
_ifcElements.insert(IFCCHILLER);
_ifcElements.insert(IFCCOIL);
_ifcElements.insert(IFCCOMMUNICATIONSAPPLIANCE);
_ifcElements.insert(IFCCOMPRESSOR);
_ifcElements.insert(IFCCONDENSER);
_ifcElements.insert(IFCCOOLEDBEAM);
_ifcElements.insert(IFCCOOLINGTOWER);
_ifcElements.insert(IFCDAMPER);
_ifcElements.insert(IFCDUCTFITTING);
_ifcElements.insert(IFCDUCTSEGMENT);
_ifcElements.insert(IFCDUCTSILENCER);
_ifcElements.insert(IFCELECTRICAPPLIANCE);
_ifcElements.insert(IFCELECTRICDISTRIBUTIONBOARD);
_ifcElements.insert(IFCELECTRICFLOWSTORAGEDEVICE);
_ifcElements.insert(IFCELECTRICGENERATOR);
_ifcElements.insert(IFCELECTRICMOTOR);
_ifcElements.insert(IFCELECTRICTIMECONTROL);
_ifcElements.insert(IFCFAN);
_ifcElements.insert(IFCFILTER);
_ifcElements.insert(IFCFIRESUPPRESSIONTERMINAL);
_ifcElements.insert(IFCFLOWINSTRUMENT);
_ifcElements.insert(IFCPROTECTIVEDEVICETRIPPINGUNIT);
_ifcElements.insert(IFCSENSOR);
_ifcElements.insert(IFCUNITARYCONTROLELEMENT);
_ifcElements.insert(IFCACTUATOR);
_ifcElements.insert(IFCALARM);
_ifcElements.insert(IFCCONTROLLER);
_ifcElements.insert(IFCFACILITY);
_ifcElements.insert(IFCFACILITYPART);
_ifcElements.insert(IFCFACILITYPARTCOMMON);
_ifcElements.insert(IFCGEOTECHNICALELEMENT);
_ifcElements.insert(IFCGEOTECHNICALSTRATUM);
_ifcElements.insert(IFCIMPACTPROTECTIONDEVICE);
_ifcElements.insert(IFCLINEARELEMENT);
_ifcElements.insert(IFCMARINEFACILITY);
_ifcElements.insert(IFCMARINEPART);
_ifcElements.insert(IFCPOSITIONINGELEMENT);
_ifcElements.insert(IFCRAILWAY);
_ifcElements.insert(IFCRAILWAYPART);
_ifcElements.insert(IFCREFERENT);
_ifcElements.insert(IFCROAD);
_ifcElements.insert(IFCROADPART);
_ifcElements.insert(IFCSIGN);
_ifcElements.insert(IFCTENDONCONDUIT);
_ifcElements.insert(IFCTRANSPORTATIONDEVICE);
_ifcElements.insert(IFCVEHICLE);
_ifcElements.insert(IFCVIBRATIONDAMPER);
_ifcElements.insert(IFCALIGNMENTCANT);
_ifcElements.insert(IFCALIGNMENTHORIZONTAL);
_ifcElements.insert(IFCALIGNMENTSEGMENT);
_ifcElements.insert(IFCALIGNMENTVERTICAL);
_ifcElements.insert(IFCBRIDGE);
_ifcElements.insert(IFCBRIDGEPART);
_ifcElements.insert(IFCBUILTELEMENT);
_ifcElements.insert(IFCCOURSE);
_ifcElements.insert(IFCDEEPFOUNDATION);
_ifcElements.insert(IFCEARTHWORKSCUT);
_ifcElements.insert(IFCEARTHWORKSELEMENT);
_ifcElements.insert(IFCEARTHWORKSFILL);
_ifcElements.insert(IFCGEOTECHNICALASSEMBLY);
_ifcElements.insert(IFCKERB);
_ifcElements.insert(IFCLINEARPOSITIONINGELEMENT);
_ifcElements.insert(IFCLIQUIDTERMINAL);
_ifcElements.insert(IFCMOBILETELECOMMUNICATIONSAPPLIANCE);
_ifcElements.insert(IFCMOORINGDEVICE);
_ifcElements.insert(IFCNAVIGATIONELEMENT);
_ifcElements.insert(IFCPAVEMENT);
_ifcElements.insert(IFCRAIL);
_ifcElements.insert(IFCREINFORCEDSOIL);
_ifcElements.insert(IFCSIGNAL);
_ifcElements.insert(IFCTRACKELEMENT);
_ifcElements.insert(IFCALIGNMENT);
_ifcElements.insert(IFCBEARING);
_ifcElements.insert(IFCBOREHOLE);
_ifcElements.insert(IFCCAISSONFOUNDATION);
_ifcElements.insert(IFCCONVEYORSEGMENT);
_ifcElements.insert(IFCDISTRIBUTIONBOARD);
_ifcElements.insert(IFCELECTRICFLOWTREATMENTDEVICE);
_ifcElements.insert(IFCGEOMODEL);
_ifcElements.insert(IFCGEOSLICE);
_schemaNames.push_back("IFC2X3");
_schemas.push_back(IFC2X3);
_schemaNames.push_back("IFC4");
_schemas.push_back(IFC4);
_schemaNames.push_back("IFC4X3");
_schemas.push_back(IFC4X3);
}
std::string IfcSchemaManager::IfcTypeCodeToType(uint32_t typeCode) const {
switch(typeCode) {
case schema::FILE_SCHEMA: return "FILE_SCHEMA";
case schema::FILE_NAME: return "FILE_NAME";
case schema::FILE_DESCRIPTION: return "FILE_DESCRIPTION";
case schema::IFCACTORROLE: return "IfcActorRole";
case schema::IFCADDRESS: return "IfcAddress";
case schema::IFCAPPLICATION: return "IfcApplication";
case schema::IFCAPPLIEDVALUE: return "IfcAppliedValue";
case schema::IFCAPPLIEDVALUERELATIONSHIP: return "IfcAppliedValueRelationship";
case schema::IFCAPPROVAL: return "IfcApproval";
case schema::IFCAPPROVALACTORRELATIONSHIP: return "IfcApprovalActorRelationship";
case schema::IFCAPPROVALPROPERTYRELATIONSHIP: return "IfcApprovalPropertyRelationship";
case schema::IFCAPPROVALRELATIONSHIP: return "IfcApprovalRelationship";
case schema::IFCBOUNDARYCONDITION: return "IfcBoundaryCondition";
case schema::IFCBOUNDARYEDGECONDITION: return "IfcBoundaryEdgeCondition";
case schema::IFCBOUNDARYFACECONDITION: return "IfcBoundaryFaceCondition";
case schema::IFCBOUNDARYNODECONDITION: return "IfcBoundaryNodeCondition";
case schema::IFCBOUNDARYNODECONDITIONWARPING: return "IfcBoundaryNodeConditionWarping";
case schema::IFCCALENDARDATE: return "IfcCalendarDate";
case schema::IFCCLASSIFICATION: return "IfcClassification";
case schema::IFCCLASSIFICATIONITEM: return "IfcClassificationItem";
case schema::IFCCLASSIFICATIONITEMRELATIONSHIP: return "IfcClassificationItemRelationship";
case schema::IFCCLASSIFICATIONNOTATION: return "IfcClassificationNotation";
case schema::IFCCLASSIFICATIONNOTATIONFACET: return "IfcClassificationNotationFacet";
case schema::IFCCOLOURSPECIFICATION: return "IfcColourSpecification";
case schema::IFCCONNECTIONGEOMETRY: return "IfcConnectionGeometry";
case schema::IFCCONNECTIONPOINTGEOMETRY: return "IfcConnectionPointGeometry";
case schema::IFCCONNECTIONPORTGEOMETRY: return "IfcConnectionPortGeometry";
case schema::IFCCONNECTIONSURFACEGEOMETRY: return "IfcConnectionSurfaceGeometry";
case schema::IFCCONSTRAINT: return "IfcConstraint";
case schema::IFCCONSTRAINTAGGREGATIONRELATIONSHIP: return "IfcConstraintAggregationRelationship";
case schema::IFCCONSTRAINTCLASSIFICATIONRELATIONSHIP: return "IfcConstraintClassificationRelationship";
case schema::IFCCONSTRAINTRELATIONSHIP: return "IfcConstraintRelationship";
case schema::IFCCOORDINATEDUNIVERSALTIMEOFFSET: return "IfcCoordinatedUniversalTimeOffset";
case schema::IFCCOSTVALUE: return "IfcCostValue";
case schema::IFCCURRENCYRELATIONSHIP: return "IfcCurrencyRelationship";
case schema::IFCCURVESTYLEFONT: return "IfcCurveStyleFont";
case schema::IFCCURVESTYLEFONTANDSCALING: return "IfcCurveStyleFontAndScaling";
case schema::IFCCURVESTYLEFONTPATTERN: return "IfcCurveStyleFontPattern";
case schema::IFCDATEANDTIME: return "IfcDateAndTime";
case schema::IFCDERIVEDUNIT: return "IfcDerivedUnit";
case schema::IFCDERIVEDUNITELEMENT: return "IfcDerivedUnitElement";
case schema::IFCDIMENSIONALEXPONENTS: return "IfcDimensionalExponents";
case schema::IFCDOCUMENTELECTRONICFORMAT: return "IfcDocumentElectronicFormat";
case schema::IFCDOCUMENTINFORMATION: return "IfcDocumentInformation";
case schema::IFCDOCUMENTINFORMATIONRELATIONSHIP: return "IfcDocumentInformationRelationship";
case schema::IFCDRAUGHTINGCALLOUTRELATIONSHIP: return "IfcDraughtingCalloutRelationship";
case schema::IFCENVIRONMENTALIMPACTVALUE: return "IfcEnvironmentalImpactValue";
case schema::IFCEXTERNALREFERENCE: return "IfcExternalReference";
case schema::IFCEXTERNALLYDEFINEDHATCHSTYLE: return "IfcExternallyDefinedHatchStyle";
case schema::IFCEXTERNALLYDEFINEDSURFACESTYLE: return "IfcExternallyDefinedSurfaceStyle";
case schema::IFCEXTERNALLYDEFINEDSYMBOL: return "IfcExternallyDefinedSymbol";
case schema::IFCEXTERNALLYDEFINEDTEXTFONT: return "IfcExternallyDefinedTextFont";
case schema::IFCGRIDAXIS: return "IfcGridAxis";
case schema::IFCIRREGULARTIMESERIESVALUE: return "IfcIrregularTimeSeriesValue";
case schema::IFCLIBRARYINFORMATION: return "IfcLibraryInformation";
case schema::IFCLIBRARYREFERENCE: return "IfcLibraryReference";
case schema::IFCLIGHTDISTRIBUTIONDATA: return "IfcLightDistributionData";
case schema::IFCLIGHTINTENSITYDISTRIBUTION: return "IfcLightIntensityDistribution";
case schema::IFCLOCALTIME: return "IfcLocalTime";
case schema::IFCMATERIAL: return "IfcMaterial";
case schema::IFCMATERIALCLASSIFICATIONRELATIONSHIP: return "IfcMaterialClassificationRelationship";
case schema::IFCMATERIALLAYER: return "IfcMaterialLayer";
case schema::IFCMATERIALLAYERSET: return "IfcMaterialLayerSet";
case schema::IFCMATERIALLAYERSETUSAGE: return "IfcMaterialLayerSetUsage";
case schema::IFCMATERIALLIST: return "IfcMaterialList";
case schema::IFCMATERIALPROPERTIES: return "IfcMaterialProperties";
case schema::IFCMEASUREWITHUNIT: return "IfcMeasureWithUnit";
case schema::IFCMECHANICALMATERIALPROPERTIES: return "IfcMechanicalMaterialProperties";
case schema::IFCMECHANICALSTEELMATERIALPROPERTIES: return "IfcMechanicalSteelMaterialProperties";
case schema::IFCMETRIC: return "IfcMetric";
case schema::IFCMONETARYUNIT: return "IfcMonetaryUnit";
case schema::IFCNAMEDUNIT: return "IfcNamedUnit";
case schema::IFCOBJECTPLACEMENT: return "IfcObjectPlacement";
case schema::IFCOBJECTIVE: return "IfcObjective";
case schema::IFCOPTICALMATERIALPROPERTIES: return "IfcOpticalMaterialProperties";
case schema::IFCORGANIZATION: return "IfcOrganization";
case schema::IFCORGANIZATIONRELATIONSHIP: return "IfcOrganizationRelationship";
case schema::IFCOWNERHISTORY: return "IfcOwnerHistory";
case schema::IFCPERSON: return "IfcPerson";
case schema::IFCPERSONANDORGANIZATION: return "IfcPersonAndOrganization";
case schema::IFCPHYSICALQUANTITY: return "IfcPhysicalQuantity";
case schema::IFCPHYSICALSIMPLEQUANTITY: return "IfcPhysicalSimpleQuantity";
case schema::IFCPOSTALADDRESS: return "IfcPostalAddress";
case schema::IFCPREDEFINEDITEM: return "IfcPreDefinedItem";
case schema::IFCPREDEFINEDSYMBOL: return "IfcPreDefinedSymbol";
case schema::IFCPREDEFINEDTERMINATORSYMBOL: return "IfcPreDefinedTerminatorSymbol";
case schema::IFCPREDEFINEDTEXTFONT: return "IfcPreDefinedTextFont";
case schema::IFCPRESENTATIONLAYERASSIGNMENT: return "IfcPresentationLayerAssignment";
case schema::IFCPRESENTATIONLAYERWITHSTYLE: return "IfcPresentationLayerWithStyle";
case schema::IFCPRESENTATIONSTYLE: return "IfcPresentationStyle";
case schema::IFCPRESENTATIONSTYLEASSIGNMENT: return "IfcPresentationStyleAssignment";
case schema::IFCPRODUCTREPRESENTATION: return "IfcProductRepresentation";
case schema::IFCPRODUCTSOFCOMBUSTIONPROPERTIES: return "IfcProductsOfCombustionProperties";
case schema::IFCPROFILEDEF: return "IfcProfileDef";
case schema::IFCPROFILEPROPERTIES: return "IfcProfileProperties";
case schema::IFCPROPERTY: return "IfcProperty";
case schema::IFCPROPERTYCONSTRAINTRELATIONSHIP: return "IfcPropertyConstraintRelationship";
case schema::IFCPROPERTYDEPENDENCYRELATIONSHIP: return "IfcPropertyDependencyRelationship";
case schema::IFCPROPERTYENUMERATION: return "IfcPropertyEnumeration";
case schema::IFCQUANTITYAREA: return "IfcQuantityArea";
case schema::IFCQUANTITYCOUNT: return "IfcQuantityCount";
case schema::IFCQUANTITYLENGTH: return "IfcQuantityLength";
case schema::IFCQUANTITYTIME: return "IfcQuantityTime";
case schema::IFCQUANTITYVOLUME: return "IfcQuantityVolume";
case schema::IFCQUANTITYWEIGHT: return "IfcQuantityWeight";
case schema::IFCREFERENCESVALUEDOCUMENT: return "IfcReferencesValueDocument";
case schema::IFCREINFORCEMENTBARPROPERTIES: return "IfcReinforcementBarProperties";
case schema::IFCRELAXATION: return "IfcRelaxation";
case schema::IFCREPRESENTATION: return "IfcRepresentation";
case schema::IFCREPRESENTATIONCONTEXT: return "IfcRepresentationContext";
case schema::IFCREPRESENTATIONITEM: return "IfcRepresentationItem";
case schema::IFCREPRESENTATIONMAP: return "IfcRepresentationMap";
case schema::IFCRIBPLATEPROFILEPROPERTIES: return "IfcRibPlateProfileProperties";
case schema::IFCROOT: return "IfcRoot";
case schema::IFCSIUNIT: return "IfcSIUnit";
case schema::IFCSECTIONPROPERTIES: return "IfcSectionProperties";
case schema::IFCSECTIONREINFORCEMENTPROPERTIES: return "IfcSectionReinforcementProperties";
case schema::IFCSHAPEASPECT: return "IfcShapeAspect";
case schema::IFCSHAPEMODEL: return "IfcShapeModel";
case schema::IFCSHAPEREPRESENTATION: return "IfcShapeRepresentation";
case schema::IFCSIMPLEPROPERTY: return "IfcSimpleProperty";
case schema::IFCSTRUCTURALCONNECTIONCONDITION: return "IfcStructuralConnectionCondition";
case schema::IFCSTRUCTURALLOAD: return "IfcStructuralLoad";
case schema::IFCSTRUCTURALLOADSTATIC: return "IfcStructuralLoadStatic";
case schema::IFCSTRUCTURALLOADTEMPERATURE: return "IfcStructuralLoadTemperature";
case schema::IFCSTYLEMODEL: return "IfcStyleModel";
case schema::IFCSTYLEDITEM: return "IfcStyledItem";
case schema::IFCSTYLEDREPRESENTATION: return "IfcStyledRepresentation";
case schema::IFCSURFACESTYLE: return "IfcSurfaceStyle";
case schema::IFCSURFACESTYLELIGHTING: return "IfcSurfaceStyleLighting";
case schema::IFCSURFACESTYLEREFRACTION: return "IfcSurfaceStyleRefraction";
case schema::IFCSURFACESTYLESHADING: return "IfcSurfaceStyleShading";
case schema::IFCSURFACESTYLEWITHTEXTURES: return "IfcSurfaceStyleWithTextures";
case schema::IFCSURFACETEXTURE: return "IfcSurfaceTexture";
case schema::IFCSYMBOLSTYLE: return "IfcSymbolStyle";
case schema::IFCTABLE: return "IfcTable";
case schema::IFCTABLEROW: return "IfcTableRow";
case schema::IFCTELECOMADDRESS: return "IfcTelecomAddress";
case schema::IFCTEXTSTYLE: return "IfcTextStyle";
case schema::IFCTEXTSTYLEFONTMODEL: return "IfcTextStyleFontModel";
case schema::IFCTEXTSTYLEFORDEFINEDFONT: return "IfcTextStyleForDefinedFont";
case schema::IFCTEXTSTYLETEXTMODEL: return "IfcTextStyleTextModel";
case schema::IFCTEXTSTYLEWITHBOXCHARACTERISTICS: return "IfcTextStyleWithBoxCharacteristics";
case schema::IFCTEXTURECOORDINATE: return "IfcTextureCoordinate";
case schema::IFCTEXTURECOORDINATEGENERATOR: return "IfcTextureCoordinateGenerator";
case schema::IFCTEXTUREMAP: return "IfcTextureMap";
case schema::IFCTEXTUREVERTEX: return "IfcTextureVertex";
case schema::IFCTHERMALMATERIALPROPERTIES: return "IfcThermalMaterialProperties";
case schema::IFCTIMESERIES: return "IfcTimeSeries";
case schema::IFCTIMESERIESREFERENCERELATIONSHIP: return "IfcTimeSeriesReferenceRelationship";
case schema::IFCTIMESERIESVALUE: return "IfcTimeSeriesValue";
case schema::IFCTOPOLOGICALREPRESENTATIONITEM: return "IfcTopologicalRepresentationItem";
case schema::IFCTOPOLOGYREPRESENTATION: return "IfcTopologyRepresentation";
case schema::IFCUNITASSIGNMENT: return "IfcUnitAssignment";
case schema::IFCVERTEX: return "IfcVertex";
case schema::IFCVERTEXBASEDTEXTUREMAP: return "IfcVertexBasedTextureMap";
case schema::IFCVERTEXPOINT: return "IfcVertexPoint";
case schema::IFCVIRTUALGRIDINTERSECTION: return "IfcVirtualGridIntersection";
case schema::IFCWATERPROPERTIES: return "IfcWaterProperties";
case schema::IFCANNOTATIONOCCURRENCE: return "IfcAnnotationOccurrence";
case schema::IFCANNOTATIONSURFACEOCCURRENCE: return "IfcAnnotationSurfaceOccurrence";
case schema::IFCANNOTATIONSYMBOLOCCURRENCE: return "IfcAnnotationSymbolOccurrence";
case schema::IFCANNOTATIONTEXTOCCURRENCE: return "IfcAnnotationTextOccurrence";
case schema::IFCARBITRARYCLOSEDPROFILEDEF: return "IfcArbitraryClosedProfileDef";
case schema::IFCARBITRARYOPENPROFILEDEF: return "IfcArbitraryOpenProfileDef";
case schema::IFCARBITRARYPROFILEDEFWITHVOIDS: return "IfcArbitraryProfileDefWithVoids";
case schema::IFCBLOBTEXTURE: return "IfcBlobTexture";
case schema::IFCCENTERLINEPROFILEDEF: return "IfcCenterLineProfileDef";
case schema::IFCCLASSIFICATIONREFERENCE: return "IfcClassificationReference";
case schema::IFCCOLOURRGB: return "IfcColourRgb";
case schema::IFCCOMPLEXPROPERTY: return "IfcComplexProperty";
case schema::IFCCOMPOSITEPROFILEDEF: return "IfcCompositeProfileDef";
case schema::IFCCONNECTEDFACESET: return "IfcConnectedFaceSet";
case schema::IFCCONNECTIONCURVEGEOMETRY: return "IfcConnectionCurveGeometry";
case schema::IFCCONNECTIONPOINTECCENTRICITY: return "IfcConnectionPointEccentricity";
case schema::IFCCONTEXTDEPENDENTUNIT: return "IfcContextDependentUnit";
case schema::IFCCONVERSIONBASEDUNIT: return "IfcConversionBasedUnit";
case schema::IFCCURVESTYLE: return "IfcCurveStyle";
case schema::IFCDERIVEDPROFILEDEF: return "IfcDerivedProfileDef";
case schema::IFCDIMENSIONCALLOUTRELATIONSHIP: return "IfcDimensionCalloutRelationship";
case schema::IFCDIMENSIONPAIR: return "IfcDimensionPair";
case schema::IFCDOCUMENTREFERENCE: return "IfcDocumentReference";
case schema::IFCDRAUGHTINGPREDEFINEDTEXTFONT: return "IfcDraughtingPreDefinedTextFont";
case schema::IFCEDGE: return "IfcEdge";
case schema::IFCEDGECURVE: return "IfcEdgeCurve";
case schema::IFCEXTENDEDMATERIALPROPERTIES: return "IfcExtendedMaterialProperties";
case schema::IFCFACE: return "IfcFace";
case schema::IFCFACEBOUND: return "IfcFaceBound";
case schema::IFCFACEOUTERBOUND: return "IfcFaceOuterBound";
case schema::IFCFACESURFACE: return "IfcFaceSurface";
case schema::IFCFAILURECONNECTIONCONDITION: return "IfcFailureConnectionCondition";
case schema::IFCFILLAREASTYLE: return "IfcFillAreaStyle";
case schema::IFCFUELPROPERTIES: return "IfcFuelProperties";
case schema::IFCGENERALMATERIALPROPERTIES: return "IfcGeneralMaterialProperties";
case schema::IFCGENERALPROFILEPROPERTIES: return "IfcGeneralProfileProperties";
case schema::IFCGEOMETRICREPRESENTATIONCONTEXT: return "IfcGeometricRepresentationContext";
case schema::IFCGEOMETRICREPRESENTATIONITEM: return "IfcGeometricRepresentationItem";
case schema::IFCGEOMETRICREPRESENTATIONSUBCONTEXT: return "IfcGeometricRepresentationSubContext";
case schema::IFCGEOMETRICSET: return "IfcGeometricSet";
case schema::IFCGRIDPLACEMENT: return "IfcGridPlacement";
case schema::IFCHALFSPACESOLID: return "IfcHalfSpaceSolid";
case schema::IFCHYGROSCOPICMATERIALPROPERTIES: return "IfcHygroscopicMaterialProperties";
case schema::IFCIMAGETEXTURE: return "IfcImageTexture";
case schema::IFCIRREGULARTIMESERIES: return "IfcIrregularTimeSeries";
case schema::IFCLIGHTSOURCE: return "IfcLightSource";
case schema::IFCLIGHTSOURCEAMBIENT: return "IfcLightSourceAmbient";
case schema::IFCLIGHTSOURCEDIRECTIONAL: return "IfcLightSourceDirectional";
case schema::IFCLIGHTSOURCEGONIOMETRIC: return "IfcLightSourceGoniometric";
case schema::IFCLIGHTSOURCEPOSITIONAL: return "IfcLightSourcePositional";
case schema::IFCLIGHTSOURCESPOT: return "IfcLightSourceSpot";
case schema::IFCLOCALPLACEMENT: return "IfcLocalPlacement";
case schema::IFCLOOP: return "IfcLoop";
case schema::IFCMAPPEDITEM: return "IfcMappedItem";
case schema::IFCMATERIALDEFINITIONREPRESENTATION: return "IfcMaterialDefinitionRepresentation";
case schema::IFCMECHANICALCONCRETEMATERIALPROPERTIES: return "IfcMechanicalConcreteMaterialProperties";
case schema::IFCOBJECTDEFINITION: return "IfcObjectDefinition";
case schema::IFCONEDIRECTIONREPEATFACTOR: return "IfcOneDirectionRepeatFactor";
case schema::IFCOPENSHELL: return "IfcOpenShell";
case schema::IFCORIENTEDEDGE: return "IfcOrientedEdge";
case schema::IFCPARAMETERIZEDPROFILEDEF: return "IfcParameterizedProfileDef";
case schema::IFCPATH: return "IfcPath";
case schema::IFCPHYSICALCOMPLEXQUANTITY: return "IfcPhysicalComplexQuantity";
case schema::IFCPIXELTEXTURE: return "IfcPixelTexture";
case schema::IFCPLACEMENT: return "IfcPlacement";
case schema::IFCPLANAREXTENT: return "IfcPlanarExtent";
case schema::IFCPOINT: return "IfcPoint";
case schema::IFCPOINTONCURVE: return "IfcPointOnCurve";
case schema::IFCPOINTONSURFACE: return "IfcPointOnSurface";
case schema::IFCPOLYLOOP: return "IfcPolyLoop";
case schema::IFCPOLYGONALBOUNDEDHALFSPACE: return "IfcPolygonalBoundedHalfSpace";
case schema::IFCPREDEFINEDCOLOUR: return "IfcPreDefinedColour";
case schema::IFCPREDEFINEDCURVEFONT: return "IfcPreDefinedCurveFont";
case schema::IFCPREDEFINEDDIMENSIONSYMBOL: return "IfcPreDefinedDimensionSymbol";
case schema::IFCPREDEFINEDPOINTMARKERSYMBOL: return "IfcPreDefinedPointMarkerSymbol";
case schema::IFCPRODUCTDEFINITIONSHAPE: return "IfcProductDefinitionShape";
case schema::IFCPROPERTYBOUNDEDVALUE: return "IfcPropertyBoundedValue";
case schema::IFCPROPERTYDEFINITION: return "IfcPropertyDefinition";
case schema::IFCPROPERTYENUMERATEDVALUE: return "IfcPropertyEnumeratedValue";
case schema::IFCPROPERTYLISTVALUE: return "IfcPropertyListValue";
case schema::IFCPROPERTYREFERENCEVALUE: return "IfcPropertyReferenceValue";
case schema::IFCPROPERTYSETDEFINITION: return "IfcPropertySetDefinition";
case schema::IFCPROPERTYSINGLEVALUE: return "IfcPropertySingleValue";
case schema::IFCPROPERTYTABLEVALUE: return "IfcPropertyTableValue";
case schema::IFCRECTANGLEPROFILEDEF: return "IfcRectangleProfileDef";
case schema::IFCREGULARTIMESERIES: return "IfcRegularTimeSeries";
case schema::IFCREINFORCEMENTDEFINITIONPROPERTIES: return "IfcReinforcementDefinitionProperties";
case schema::IFCRELATIONSHIP: return "IfcRelationship";
case schema::IFCROUNDEDRECTANGLEPROFILEDEF: return "IfcRoundedRectangleProfileDef";
case schema::IFCSECTIONEDSPINE: return "IfcSectionedSpine";
case schema::IFCSERVICELIFEFACTOR: return "IfcServiceLifeFactor";
case schema::IFCSHELLBASEDSURFACEMODEL: return "IfcShellBasedSurfaceModel";
case schema::IFCSLIPPAGECONNECTIONCONDITION: return "IfcSlippageConnectionCondition";
case schema::IFCSOLIDMODEL: return "IfcSolidModel";
case schema::IFCSOUNDPROPERTIES: return "IfcSoundProperties";
case schema::IFCSOUNDVALUE: return "IfcSoundValue";
case schema::IFCSPACETHERMALLOADPROPERTIES: return "IfcSpaceThermalLoadProperties";
case schema::IFCSTRUCTURALLOADLINEARFORCE: return "IfcStructuralLoadLinearForce";
case schema::IFCSTRUCTURALLOADPLANARFORCE: return "IfcStructuralLoadPlanarForce";
case schema::IFCSTRUCTURALLOADSINGLEDISPLACEMENT: return "IfcStructuralLoadSingleDisplacement";
case schema::IFCSTRUCTURALLOADSINGLEDISPLACEMENTDISTORTION: return "IfcStructuralLoadSingleDisplacementDistortion";
case schema::IFCSTRUCTURALLOADSINGLEFORCE: return "IfcStructuralLoadSingleForce";
case schema::IFCSTRUCTURALLOADSINGLEFORCEWARPING: return "IfcStructuralLoadSingleForceWarping";
case schema::IFCSTRUCTURALPROFILEPROPERTIES: return "IfcStructuralProfileProperties";
case schema::IFCSTRUCTURALSTEELPROFILEPROPERTIES: return "IfcStructuralSteelProfileProperties";
case schema::IFCSUBEDGE: return "IfcSubedge";
case schema::IFCSURFACE: return "IfcSurface";
case schema::IFCSURFACESTYLERENDERING: return "IfcSurfaceStyleRendering";
case schema::IFCSWEPTAREASOLID: return "IfcSweptAreaSolid";
case schema::IFCSWEPTDISKSOLID: return "IfcSweptDiskSolid";
case schema::IFCSWEPTSURFACE: return "IfcSweptSurface";
case schema::IFCTSHAPEPROFILEDEF: return "IfcTShapeProfileDef";
case schema::IFCTERMINATORSYMBOL: return "IfcTerminatorSymbol";
case schema::IFCTEXTLITERAL: return "IfcTextLiteral";
case schema::IFCTEXTLITERALWITHEXTENT: return "IfcTextLiteralWithExtent";
case schema::IFCTRAPEZIUMPROFILEDEF: return "IfcTrapeziumProfileDef";
case schema::IFCTWODIRECTIONREPEATFACTOR: return "IfcTwoDirectionRepeatFactor";
case schema::IFCTYPEOBJECT: return "IfcTypeObject";
case schema::IFCTYPEPRODUCT: return "IfcTypeProduct";
case schema::IFCUSHAPEPROFILEDEF: return "IfcUShapeProfileDef";
case schema::IFCVECTOR: return "IfcVector";
case schema::IFCVERTEXLOOP: return "IfcVertexLoop";
case schema::IFCWINDOWLININGPROPERTIES: return "IfcWindowLiningProperties";
case schema::IFCWINDOWPANELPROPERTIES: return "IfcWindowPanelProperties";
case schema::IFCWINDOWSTYLE: return "IfcWindowStyle";
case schema::IFCZSHAPEPROFILEDEF: return "IfcZShapeProfileDef";
case schema::IFCANNOTATIONCURVEOCCURRENCE: return "IfcAnnotationCurveOccurrence";
case schema::IFCANNOTATIONFILLAREA: return "IfcAnnotationFillArea";
case schema::IFCANNOTATIONFILLAREAOCCURRENCE: return "IfcAnnotationFillAreaOccurrence";
case schema::IFCANNOTATIONSURFACE: return "IfcAnnotationSurface";
case schema::IFCAXIS1PLACEMENT: return "IfcAxis1Placement";
case schema::IFCAXIS2PLACEMENT2D: return "IfcAxis2Placement2D";
case schema::IFCAXIS2PLACEMENT3D: return "IfcAxis2Placement3D";
case schema::IFCBOOLEANRESULT: return "IfcBooleanResult";
case schema::IFCBOUNDEDSURFACE: return "IfcBoundedSurface";
case schema::IFCBOUNDINGBOX: return "IfcBoundingBox";
case schema::IFCBOXEDHALFSPACE: return "IfcBoxedHalfSpace";
case schema::IFCCSHAPEPROFILEDEF: return "IfcCShapeProfileDef";
case schema::IFCCARTESIANPOINT: return "IfcCartesianPoint";
case schema::IFCCARTESIANTRANSFORMATIONOPERATOR: return "IfcCartesianTransformationOperator";
case schema::IFCCARTESIANTRANSFORMATIONOPERATOR2D: return "IfcCartesianTransformationOperator2D";
case schema::IFCCARTESIANTRANSFORMATIONOPERATOR2DNONUNIFORM: return "IfcCartesianTransformationOperator2DnonUniform";
case schema::IFCCARTESIANTRANSFORMATIONOPERATOR3D: return "IfcCartesianTransformationOperator3D";
case schema::IFCCARTESIANTRANSFORMATIONOPERATOR3DNONUNIFORM: return "IfcCartesianTransformationOperator3DnonUniform";
case schema::IFCCIRCLEPROFILEDEF: return "IfcCircleProfileDef";
case schema::IFCCLOSEDSHELL: return "IfcClosedShell";
case schema::IFCCOMPOSITECURVESEGMENT: return "IfcCompositeCurveSegment";
case schema::IFCCRANERAILASHAPEPROFILEDEF: return "IfcCraneRailAShapeProfileDef";
case schema::IFCCRANERAILFSHAPEPROFILEDEF: return "IfcCraneRailFShapeProfileDef";
case schema::IFCCSGPRIMITIVE3D: return "IfcCsgPrimitive3D";
case schema::IFCCSGSOLID: return "IfcCsgSolid";
case schema::IFCCURVE: return "IfcCurve";
case schema::IFCCURVEBOUNDEDPLANE: return "IfcCurveBoundedPlane";
case schema::IFCDEFINEDSYMBOL: return "IfcDefinedSymbol";
case schema::IFCDIMENSIONCURVE: return "IfcDimensionCurve";
case schema::IFCDIMENSIONCURVETERMINATOR: return "IfcDimensionCurveTerminator";
case schema::IFCDIRECTION: return "IfcDirection";
case schema::IFCDOORLININGPROPERTIES: return "IfcDoorLiningProperties";
case schema::IFCDOORPANELPROPERTIES: return "IfcDoorPanelProperties";
case schema::IFCDOORSTYLE: return "IfcDoorStyle";
case schema::IFCDRAUGHTINGCALLOUT: return "IfcDraughtingCallout";
case schema::IFCDRAUGHTINGPREDEFINEDCOLOUR: return "IfcDraughtingPreDefinedColour";
case schema::IFCDRAUGHTINGPREDEFINEDCURVEFONT: return "IfcDraughtingPreDefinedCurveFont";
case schema::IFCEDGELOOP: return "IfcEdgeLoop";
case schema::IFCELEMENTQUANTITY: return "IfcElementQuantity";
case schema::IFCELEMENTTYPE: return "IfcElementType";
case schema::IFCELEMENTARYSURFACE: return "IfcElementarySurface";
case schema::IFCELLIPSEPROFILEDEF: return "IfcEllipseProfileDef";
case schema::IFCENERGYPROPERTIES: return "IfcEnergyProperties";
case schema::IFCEXTRUDEDAREASOLID: return "IfcExtrudedAreaSolid";
case schema::IFCFACEBASEDSURFACEMODEL: return "IfcFaceBasedSurfaceModel";
case schema::IFCFILLAREASTYLEHATCHING: return "IfcFillAreaStyleHatching";
case schema::IFCFILLAREASTYLETILESYMBOLWITHSTYLE: return "IfcFillAreaStyleTileSymbolWithStyle";
case schema::IFCFILLAREASTYLETILES: return "IfcFillAreaStyleTiles";
case schema::IFCFLUIDFLOWPROPERTIES: return "IfcFluidFlowProperties";
case schema::IFCFURNISHINGELEMENTTYPE: return "IfcFurnishingElementType";
case schema::IFCFURNITURETYPE: return "IfcFurnitureType";
case schema::IFCGEOMETRICCURVESET: return "IfcGeometricCurveSet";
case schema::IFCISHAPEPROFILEDEF: return "IfcIShapeProfileDef";
case schema::IFCLSHAPEPROFILEDEF: return "IfcLShapeProfileDef";
case schema::IFCLINE: return "IfcLine";
case schema::IFCMANIFOLDSOLIDBREP: return "IfcManifoldSolidBrep";
case schema::IFCOBJECT: return "IfcObject";
case schema::IFCOFFSETCURVE2D: return "IfcOffsetCurve2D";
case schema::IFCOFFSETCURVE3D: return "IfcOffsetCurve3D";
case schema::IFCPERMEABLECOVERINGPROPERTIES: return "IfcPermeableCoveringProperties";
case schema::IFCPLANARBOX: return "IfcPlanarBox";
case schema::IFCPLANE: return "IfcPlane";
case schema::IFCPROCESS: return "IfcProcess";
case schema::IFCPRODUCT: return "IfcProduct";
case schema::IFCPROJECT: return "IfcProject";
case schema::IFCPROJECTIONCURVE: return "IfcProjectionCurve";
case schema::IFCPROPERTYSET: return "IfcPropertySet";
case schema::IFCPROXY: return "IfcProxy";
case schema::IFCRECTANGLEHOLLOWPROFILEDEF: return "IfcRectangleHollowProfileDef";
case schema::IFCRECTANGULARPYRAMID: return "IfcRectangularPyramid";
case schema::IFCRECTANGULARTRIMMEDSURFACE: return "IfcRectangularTrimmedSurface";
case schema::IFCRELASSIGNS: return "IfcRelAssigns";
case schema::IFCRELASSIGNSTOACTOR: return "IfcRelAssignsToActor";
case schema::IFCRELASSIGNSTOCONTROL: return "IfcRelAssignsToControl";
case schema::IFCRELASSIGNSTOGROUP: return "IfcRelAssignsToGroup";
case schema::IFCRELASSIGNSTOPROCESS: return "IfcRelAssignsToProcess";
case schema::IFCRELASSIGNSTOPRODUCT: return "IfcRelAssignsToProduct";
case schema::IFCRELASSIGNSTOPROJECTORDER: return "IfcRelAssignsToProjectOrder";
case schema::IFCRELASSIGNSTORESOURCE: return "IfcRelAssignsToResource";
case schema::IFCRELASSOCIATES: return "IfcRelAssociates";
case schema::IFCRELASSOCIATESAPPLIEDVALUE: return "IfcRelAssociatesAppliedValue";
case schema::IFCRELASSOCIATESAPPROVAL: return "IfcRelAssociatesApproval";
case schema::IFCRELASSOCIATESCLASSIFICATION: return "IfcRelAssociatesClassification";
case schema::IFCRELASSOCIATESCONSTRAINT: return "IfcRelAssociatesConstraint";
case schema::IFCRELASSOCIATESDOCUMENT: return "IfcRelAssociatesDocument";
case schema::IFCRELASSOCIATESLIBRARY: return "IfcRelAssociatesLibrary";
case schema::IFCRELASSOCIATESMATERIAL: return "IfcRelAssociatesMaterial";
case schema::IFCRELASSOCIATESPROFILEPROPERTIES: return "IfcRelAssociatesProfileProperties";
case schema::IFCRELCONNECTS: return "IfcRelConnects";
case schema::IFCRELCONNECTSELEMENTS: return "IfcRelConnectsElements";
case schema::IFCRELCONNECTSPATHELEMENTS: return "IfcRelConnectsPathElements";
case schema::IFCRELCONNECTSPORTTOELEMENT: return "IfcRelConnectsPortToElement";
case schema::IFCRELCONNECTSPORTS: return "IfcRelConnectsPorts";
case schema::IFCRELCONNECTSSTRUCTURALACTIVITY: return "IfcRelConnectsStructuralActivity";
case schema::IFCRELCONNECTSSTRUCTURALELEMENT: return "IfcRelConnectsStructuralElement";
case schema::IFCRELCONNECTSSTRUCTURALMEMBER: return "IfcRelConnectsStructuralMember";
case schema::IFCRELCONNECTSWITHECCENTRICITY: return "IfcRelConnectsWithEccentricity";
case schema::IFCRELCONNECTSWITHREALIZINGELEMENTS: return "IfcRelConnectsWithRealizingElements";
case schema::IFCRELCONTAINEDINSPATIALSTRUCTURE: return "IfcRelContainedInSpatialStructure";
case schema::IFCRELCOVERSBLDGELEMENTS: return "IfcRelCoversBldgElements";
case schema::IFCRELCOVERSSPACES: return "IfcRelCoversSpaces";
case schema::IFCRELDECOMPOSES: return "IfcRelDecomposes";
case schema::IFCRELDEFINES: return "IfcRelDefines";
case schema::IFCRELDEFINESBYPROPERTIES: return "IfcRelDefinesByProperties";
case schema::IFCRELDEFINESBYTYPE: return "IfcRelDefinesByType";
case schema::IFCRELFILLSELEMENT: return "IfcRelFillsElement";
case schema::IFCRELFLOWCONTROLELEMENTS: return "IfcRelFlowControlElements";
case schema::IFCRELINTERACTIONREQUIREMENTS: return "IfcRelInteractionRequirements";
case schema::IFCRELNESTS: return "IfcRelNests";
case schema::IFCRELOCCUPIESSPACES: return "IfcRelOccupiesSpaces";
case schema::IFCRELOVERRIDESPROPERTIES: return "IfcRelOverridesProperties";
case schema::IFCRELPROJECTSELEMENT: return "IfcRelProjectsElement";
case schema::IFCRELREFERENCEDINSPATIALSTRUCTURE: return "IfcRelReferencedInSpatialStructure";
case schema::IFCRELSCHEDULESCOSTITEMS: return "IfcRelSchedulesCostItems";
case schema::IFCRELSEQUENCE: return "IfcRelSequence";
case schema::IFCRELSERVICESBUILDINGS: return "IfcRelServicesBuildings";
case schema::IFCRELSPACEBOUNDARY: return "IfcRelSpaceBoundary";
case schema::IFCRELVOIDSELEMENT: return "IfcRelVoidsElement";
case schema::IFCRESOURCE: return "IfcResource";
case schema::IFCREVOLVEDAREASOLID: return "IfcRevolvedAreaSolid";
case schema::IFCRIGHTCIRCULARCONE: return "IfcRightCircularCone";
case schema::IFCRIGHTCIRCULARCYLINDER: return "IfcRightCircularCylinder";
case schema::IFCSPATIALSTRUCTUREELEMENT: return "IfcSpatialStructureElement";
case schema::IFCSPATIALSTRUCTUREELEMENTTYPE: return "IfcSpatialStructureElementType";
case schema::IFCSPHERE: return "IfcSphere";
case schema::IFCSTRUCTURALACTIVITY: return "IfcStructuralActivity";
case schema::IFCSTRUCTURALITEM: return "IfcStructuralItem";
case schema::IFCSTRUCTURALMEMBER: return "IfcStructuralMember";
case schema::IFCSTRUCTURALREACTION: return "IfcStructuralReaction";
case schema::IFCSTRUCTURALSURFACEMEMBER: return "IfcStructuralSurfaceMember";
case schema::IFCSTRUCTURALSURFACEMEMBERVARYING: return "IfcStructuralSurfaceMemberVarying";
case schema::IFCSTRUCTUREDDIMENSIONCALLOUT: return "IfcStructuredDimensionCallout";
case schema::IFCSURFACECURVESWEPTAREASOLID: return "IfcSurfaceCurveSweptAreaSolid";
case schema::IFCSURFACEOFLINEAREXTRUSION: return "IfcSurfaceOfLinearExtrusion";
case schema::IFCSURFACEOFREVOLUTION: return "IfcSurfaceOfRevolution";
case schema::IFCSYSTEMFURNITUREELEMENTTYPE: return "IfcSystemFurnitureElementType";
case schema::IFCTASK: return "IfcTask";
case schema::IFCTRANSPORTELEMENTTYPE: return "IfcTransportElementType";
case schema::IFCACTOR: return "IfcActor";
case schema::IFCANNOTATION: return "IfcAnnotation";
case schema::IFCASYMMETRICISHAPEPROFILEDEF: return "IfcAsymmetricIShapeProfileDef";
case schema::IFCBLOCK: return "IfcBlock";
case schema::IFCBOOLEANCLIPPINGRESULT: return "IfcBooleanClippingResult";
case schema::IFCBOUNDEDCURVE: return "IfcBoundedCurve";
case schema::IFCBUILDING: return "IfcBuilding";
case schema::IFCBUILDINGELEMENTTYPE: return "IfcBuildingElementType";
case schema::IFCBUILDINGSTOREY: return "IfcBuildingStorey";
case schema::IFCCIRCLEHOLLOWPROFILEDEF: return "IfcCircleHollowProfileDef";
case schema::IFCCOLUMNTYPE: return "IfcColumnType";
case schema::IFCCOMPOSITECURVE: return "IfcCompositeCurve";
case schema::IFCCONIC: return "IfcConic";
case schema::IFCCONSTRUCTIONRESOURCE: return "IfcConstructionResource";
case schema::IFCCONTROL: return "IfcControl";
case schema::IFCCOSTITEM: return "IfcCostItem";
case schema::IFCCOSTSCHEDULE: return "IfcCostSchedule";
case schema::IFCCOVERINGTYPE: return "IfcCoveringType";
case schema::IFCCREWRESOURCE: return "IfcCrewResource";
case schema::IFCCURTAINWALLTYPE: return "IfcCurtainWallType";
case schema::IFCDIMENSIONCURVEDIRECTEDCALLOUT: return "IfcDimensionCurveDirectedCallout";
case schema::IFCDISTRIBUTIONELEMENTTYPE: return "IfcDistributionElementType";
case schema::IFCDISTRIBUTIONFLOWELEMENTTYPE: return "IfcDistributionFlowElementType";
case schema::IFCELECTRICALBASEPROPERTIES: return "IfcElectricalBaseProperties";
case schema::IFCELEMENT: return "IfcElement";
case schema::IFCELEMENTASSEMBLY: return "IfcElementAssembly";
case schema::IFCELEMENTCOMPONENT: return "IfcElementComponent";
case schema::IFCELEMENTCOMPONENTTYPE: return "IfcElementComponentType";
case schema::IFCELLIPSE: return "IfcEllipse";
case schema::IFCENERGYCONVERSIONDEVICETYPE: return "IfcEnergyConversionDeviceType";
case schema::IFCEQUIPMENTELEMENT: return "IfcEquipmentElement";
case schema::IFCEQUIPMENTSTANDARD: return "IfcEquipmentStandard";
case schema::IFCEVAPORATIVECOOLERTYPE: return "IfcEvaporativeCoolerType";
case schema::IFCEVAPORATORTYPE: return "IfcEvaporatorType";
case schema::IFCFACETEDBREP: return "IfcFacetedBrep";
case schema::IFCFACETEDBREPWITHVOIDS: return "IfcFacetedBrepWithVoids";
case schema::IFCFASTENER: return "IfcFastener";
case schema::IFCFASTENERTYPE: return "IfcFastenerType";
case schema::IFCFEATUREELEMENT: return "IfcFeatureElement";
case schema::IFCFEATUREELEMENTADDITION: return "IfcFeatureElementAddition";
case schema::IFCFEATUREELEMENTSUBTRACTION: return "IfcFeatureElementSubtraction";
case schema::IFCFLOWCONTROLLERTYPE: return "IfcFlowControllerType";
case schema::IFCFLOWFITTINGTYPE: return "IfcFlowFittingType";
case schema::IFCFLOWMETERTYPE: return "IfcFlowMeterType";
case schema::IFCFLOWMOVINGDEVICETYPE: return "IfcFlowMovingDeviceType";
case schema::IFCFLOWSEGMENTTYPE: return "IfcFlowSegmentType";
case schema::IFCFLOWSTORAGEDEVICETYPE: return "IfcFlowStorageDeviceType";
case schema::IFCFLOWTERMINALTYPE: return "IfcFlowTerminalType";
case schema::IFCFLOWTREATMENTDEVICETYPE: return "IfcFlowTreatmentDeviceType";
case schema::IFCFURNISHINGELEMENT: return "IfcFurnishingElement";
case schema::IFCFURNITURESTANDARD: return "IfcFurnitureStandard";
case schema::IFCGASTERMINALTYPE: return "IfcGasTerminalType";
case schema::IFCGRID: return "IfcGrid";
case schema::IFCGROUP: return "IfcGroup";
case schema::IFCHEATEXCHANGERTYPE: return "IfcHeatExchangerType";
case schema::IFCHUMIDIFIERTYPE: return "IfcHumidifierType";
case schema::IFCINVENTORY: return "IfcInventory";
case schema::IFCJUNCTIONBOXTYPE: return "IfcJunctionBoxType";
case schema::IFCLABORRESOURCE: return "IfcLaborResource";
case schema::IFCLAMPTYPE: return "IfcLampType";
case schema::IFCLIGHTFIXTURETYPE: return "IfcLightFixtureType";
case schema::IFCLINEARDIMENSION: return "IfcLinearDimension";
case schema::IFCMECHANICALFASTENER: return "IfcMechanicalFastener";
case schema::IFCMECHANICALFASTENERTYPE: return "IfcMechanicalFastenerType";
case schema::IFCMEMBERTYPE: return "IfcMemberType";
case schema::IFCMOTORCONNECTIONTYPE: return "IfcMotorConnectionType";
case schema::IFCMOVE: return "IfcMove";
case schema::IFCOCCUPANT: return "IfcOccupant";
case schema::IFCOPENINGELEMENT: return "IfcOpeningElement";
case schema::IFCORDERACTION: return "IfcOrderAction";
case schema::IFCOUTLETTYPE: return "IfcOutletType";
case schema::IFCPERFORMANCEHISTORY: return "IfcPerformanceHistory";
case schema::IFCPERMIT: return "IfcPermit";
case schema::IFCPIPEFITTINGTYPE: return "IfcPipeFittingType";
case schema::IFCPIPESEGMENTTYPE: return "IfcPipeSegmentType";
case schema::IFCPLATETYPE: return "IfcPlateType";
case schema::IFCPOLYLINE: return "IfcPolyline";
case schema::IFCPORT: return "IfcPort";
case schema::IFCPROCEDURE: return "IfcProcedure";
case schema::IFCPROJECTORDER: return "IfcProjectOrder";
case schema::IFCPROJECTORDERRECORD: return "IfcProjectOrderRecord";
case schema::IFCPROJECTIONELEMENT: return "IfcProjectionElement";
case schema::IFCPROTECTIVEDEVICETYPE: return "IfcProtectiveDeviceType";
case schema::IFCPUMPTYPE: return "IfcPumpType";
case schema::IFCRADIUSDIMENSION: return "IfcRadiusDimension";
case schema::IFCRAILINGTYPE: return "IfcRailingType";
case schema::IFCRAMPFLIGHTTYPE: return "IfcRampFlightType";
case schema::IFCRELAGGREGATES: return "IfcRelAggregates";
case schema::IFCRELASSIGNSTASKS: return "IfcRelAssignsTasks";
case schema::IFCSANITARYTERMINALTYPE: return "IfcSanitaryTerminalType";
case schema::IFCSCHEDULETIMECONTROL: return "IfcScheduleTimeControl";
case schema::IFCSERVICELIFE: return "IfcServiceLife";
case schema::IFCSITE: return "IfcSite";
case schema::IFCSLABTYPE: return "IfcSlabType";
case schema::IFCSPACE: return "IfcSpace";
case schema::IFCSPACEHEATERTYPE: return "IfcSpaceHeaterType";
case schema::IFCSPACEPROGRAM: return "IfcSpaceProgram";
case schema::IFCSPACETYPE: return "IfcSpaceType";
case schema::IFCSTACKTERMINALTYPE: return "IfcStackTerminalType";
case schema::IFCSTAIRFLIGHTTYPE: return "IfcStairFlightType";
case schema::IFCSTRUCTURALACTION: return "IfcStructuralAction";
case schema::IFCSTRUCTURALCONNECTION: return "IfcStructuralConnection";
case schema::IFCSTRUCTURALCURVECONNECTION: return "IfcStructuralCurveConnection";
case schema::IFCSTRUCTURALCURVEMEMBER: return "IfcStructuralCurveMember";
case schema::IFCSTRUCTURALCURVEMEMBERVARYING: return "IfcStructuralCurveMemberVarying";
case schema::IFCSTRUCTURALLINEARACTION: return "IfcStructuralLinearAction";
case schema::IFCSTRUCTURALLINEARACTIONVARYING: return "IfcStructuralLinearActionVarying";
case schema::IFCSTRUCTURALLOADGROUP: return "IfcStructuralLoadGroup";
case schema::IFCSTRUCTURALPLANARACTION: return "IfcStructuralPlanarAction";
case schema::IFCSTRUCTURALPLANARACTIONVARYING: return "IfcStructuralPlanarActionVarying";
case schema::IFCSTRUCTURALPOINTACTION: return "IfcStructuralPointAction";
case schema::IFCSTRUCTURALPOINTCONNECTION: return "IfcStructuralPointConnection";
case schema::IFCSTRUCTURALPOINTREACTION: return "IfcStructuralPointReaction";
case schema::IFCSTRUCTURALRESULTGROUP: return "IfcStructuralResultGroup";
case schema::IFCSTRUCTURALSURFACECONNECTION: return "IfcStructuralSurfaceConnection";
case schema::IFCSUBCONTRACTRESOURCE: return "IfcSubContractResource";
case schema::IFCSWITCHINGDEVICETYPE: return "IfcSwitchingDeviceType";
case schema::IFCSYSTEM: return "IfcSystem";
case schema::IFCTANKTYPE: return "IfcTankType";
case schema::IFCTIMESERIESSCHEDULE: return "IfcTimeSeriesSchedule";
case schema::IFCTRANSFORMERTYPE: return "IfcTransformerType";
case schema::IFCTRANSPORTELEMENT: return "IfcTransportElement";
case schema::IFCTRIMMEDCURVE: return "IfcTrimmedCurve";
case schema::IFCTUBEBUNDLETYPE: return "IfcTubeBundleType";
case schema::IFCUNITARYEQUIPMENTTYPE: return "IfcUnitaryEquipmentType";
case schema::IFCVALVETYPE: return "IfcValveType";
case schema::IFCVIRTUALELEMENT: return "IfcVirtualElement";
case schema::IFCWALLTYPE: return "IfcWallType";
case schema::IFCWASTETERMINALTYPE: return "IfcWasteTerminalType";
case schema::IFCWORKCONTROL: return "IfcWorkControl";
case schema::IFCWORKPLAN: return "IfcWorkPlan";
case schema::IFCWORKSCHEDULE: return "IfcWorkSchedule";
case schema::IFCZONE: return "IfcZone";
case schema::IFC2DCOMPOSITECURVE: return "Ifc2DCompositeCurve";
case schema::IFCACTIONREQUEST: return "IfcActionRequest";
case schema::IFCAIRTERMINALBOXTYPE: return "IfcAirTerminalBoxType";
case schema::IFCAIRTERMINALTYPE: return "IfcAirTerminalType";
case schema::IFCAIRTOAIRHEATRECOVERYTYPE: return "IfcAirToAirHeatRecoveryType";
case schema::IFCANGULARDIMENSION: return "IfcAngularDimension";
case schema::IFCASSET: return "IfcAsset";
case schema::IFCBSPLINECURVE: return "IfcBSplineCurve";
case schema::IFCBEAMTYPE: return "IfcBeamType";
case schema::IFCBEZIERCURVE: return "IfcBezierCurve";
case schema::IFCBOILERTYPE: return "IfcBoilerType";
case schema::IFCBUILDINGELEMENT: return "IfcBuildingElement";
case schema::IFCBUILDINGELEMENTCOMPONENT: return "IfcBuildingElementComponent";
case schema::IFCBUILDINGELEMENTPART: return "IfcBuildingElementPart";
case schema::IFCBUILDINGELEMENTPROXY: return "IfcBuildingElementProxy";
case schema::IFCBUILDINGELEMENTPROXYTYPE: return "IfcBuildingElementProxyType";
case schema::IFCCABLECARRIERFITTINGTYPE: return "IfcCableCarrierFittingType";
case schema::IFCCABLECARRIERSEGMENTTYPE: return "IfcCableCarrierSegmentType";
case schema::IFCCABLESEGMENTTYPE: return "IfcCableSegmentType";
case schema::IFCCHILLERTYPE: return "IfcChillerType";
case schema::IFCCIRCLE: return "IfcCircle";
case schema::IFCCOILTYPE: return "IfcCoilType";
case schema::IFCCOLUMN: return "IfcColumn";
case schema::IFCCOMPRESSORTYPE: return "IfcCompressorType";
case schema::IFCCONDENSERTYPE: return "IfcCondenserType";
case schema::IFCCONDITION: return "IfcCondition";
case schema::IFCCONDITIONCRITERION: return "IfcConditionCriterion";
case schema::IFCCONSTRUCTIONEQUIPMENTRESOURCE: return "IfcConstructionEquipmentResource";
case schema::IFCCONSTRUCTIONMATERIALRESOURCE: return "IfcConstructionMaterialResource";
case schema::IFCCONSTRUCTIONPRODUCTRESOURCE: return "IfcConstructionProductResource";
case schema::IFCCOOLEDBEAMTYPE: return "IfcCooledBeamType";
case schema::IFCCOOLINGTOWERTYPE: return "IfcCoolingTowerType";
case schema::IFCCOVERING: return "IfcCovering";
case schema::IFCCURTAINWALL: return "IfcCurtainWall";
case schema::IFCDAMPERTYPE: return "IfcDamperType";
case schema::IFCDIAMETERDIMENSION: return "IfcDiameterDimension";
case schema::IFCDISCRETEACCESSORY: return "IfcDiscreteAccessory";
case schema::IFCDISCRETEACCESSORYTYPE: return "IfcDiscreteAccessoryType";
case schema::IFCDISTRIBUTIONCHAMBERELEMENTTYPE: return "IfcDistributionChamberElementType";
case schema::IFCDISTRIBUTIONCONTROLELEMENTTYPE: return "IfcDistributionControlElementType";
case schema::IFCDISTRIBUTIONELEMENT: return "IfcDistributionElement";
case schema::IFCDISTRIBUTIONFLOWELEMENT: return "IfcDistributionFlowElement";
case schema::IFCDISTRIBUTIONPORT: return "IfcDistributionPort";
case schema::IFCDOOR: return "IfcDoor";
case schema::IFCDUCTFITTINGTYPE: return "IfcDuctFittingType";
case schema::IFCDUCTSEGMENTTYPE: return "IfcDuctSegmentType";
case schema::IFCDUCTSILENCERTYPE: return "IfcDuctSilencerType";
case schema::IFCEDGEFEATURE: return "IfcEdgeFeature";
case schema::IFCELECTRICAPPLIANCETYPE: return "IfcElectricApplianceType";
case schema::IFCELECTRICFLOWSTORAGEDEVICETYPE: return "IfcElectricFlowStorageDeviceType";
case schema::IFCELECTRICGENERATORTYPE: return "IfcElectricGeneratorType";
case schema::IFCELECTRICHEATERTYPE: return "IfcElectricHeaterType";
case schema::IFCELECTRICMOTORTYPE: return "IfcElectricMotorType";
case schema::IFCELECTRICTIMECONTROLTYPE: return "IfcElectricTimeControlType";
case schema::IFCELECTRICALCIRCUIT: return "IfcElectricalCircuit";
case schema::IFCELECTRICALELEMENT: return "IfcElectricalElement";
case schema::IFCENERGYCONVERSIONDEVICE: return "IfcEnergyConversionDevice";
case schema::IFCFANTYPE: return "IfcFanType";
case schema::IFCFILTERTYPE: return "IfcFilterType";
case schema::IFCFIRESUPPRESSIONTERMINALTYPE: return "IfcFireSuppressionTerminalType";
case schema::IFCFLOWCONTROLLER: return "IfcFlowController";
case schema::IFCFLOWFITTING: return "IfcFlowFitting";
case schema::IFCFLOWINSTRUMENTTYPE: return "IfcFlowInstrumentType";
case schema::IFCFLOWMOVINGDEVICE: return "IfcFlowMovingDevice";
case schema::IFCFLOWSEGMENT: return "IfcFlowSegment";
case schema::IFCFLOWSTORAGEDEVICE: return "IfcFlowStorageDevice";
case schema::IFCFLOWTERMINAL: return "IfcFlowTerminal";
case schema::IFCFLOWTREATMENTDEVICE: return "IfcFlowTreatmentDevice";
case schema::IFCFOOTING: return "IfcFooting";
case schema::IFCMEMBER: return "IfcMember";
case schema::IFCPILE: return "IfcPile";
case schema::IFCPLATE: return "IfcPlate";
case schema::IFCRAILING: return "IfcRailing";
case schema::IFCRAMP: return "IfcRamp";
case schema::IFCRAMPFLIGHT: return "IfcRampFlight";
case schema::IFCRATIONALBEZIERCURVE: return "IfcRationalBezierCurve";
case schema::IFCREINFORCINGELEMENT: return "IfcReinforcingElement";
case schema::IFCREINFORCINGMESH: return "IfcReinforcingMesh";
case schema::IFCROOF: return "IfcRoof";
case schema::IFCROUNDEDEDGEFEATURE: return "IfcRoundedEdgeFeature";
case schema::IFCSENSORTYPE: return "IfcSensorType";
case schema::IFCSLAB: return "IfcSlab";
case schema::IFCSTAIR: return "IfcStair";
case schema::IFCSTAIRFLIGHT: return "IfcStairFlight";
case schema::IFCSTRUCTURALANALYSISMODEL: return "IfcStructuralAnalysisModel";
case schema::IFCTENDON: return "IfcTendon";
case schema::IFCTENDONANCHOR: return "IfcTendonAnchor";
case schema::IFCVIBRATIONISOLATORTYPE: return "IfcVibrationIsolatorType";
case schema::IFCWALL: return "IfcWall";
case schema::IFCWALLSTANDARDCASE: return "IfcWallStandardCase";
case schema::IFCWINDOW: return "IfcWindow";
case schema::IFCACTUATORTYPE: return "IfcActuatorType";
case schema::IFCALARMTYPE: return "IfcAlarmType";
case schema::IFCBEAM: return "IfcBeam";
case schema::IFCCHAMFEREDGEFEATURE: return "IfcChamferEdgeFeature";
case schema::IFCCONTROLLERTYPE: return "IfcControllerType";
case schema::IFCDISTRIBUTIONCHAMBERELEMENT: return "IfcDistributionChamberElement";
case schema::IFCDISTRIBUTIONCONTROLELEMENT: return "IfcDistributionControlElement";
case schema::IFCELECTRICDISTRIBUTIONPOINT: return "IfcElectricDistributionPoint";
case schema::IFCREINFORCINGBAR: return "IfcReinforcingBar";
case schema::IFCCONNECTIONVOLUMEGEOMETRY: return "IfcConnectionVolumeGeometry";
case schema::IFCCOORDINATEOPERATION: return "IfcCoordinateOperation";
case schema::IFCCOORDINATEREFERENCESYSTEM: return "IfcCoordinateReferenceSystem";
case schema::IFCEXTERNALINFORMATION: return "IfcExternalInformation";
case schema::IFCMAPCONVERSION: return "IfcMapConversion";
case schema::IFCMATERIALDEFINITION: return "IfcMaterialDefinition";
case schema::IFCMATERIALLAYERWITHOFFSETS: return "IfcMaterialLayerWithOffsets";
case schema::IFCMATERIALPROFILE: return "IfcMaterialProfile";
case schema::IFCMATERIALPROFILESET: return "IfcMaterialProfileSet";
case schema::IFCMATERIALPROFILEWITHOFFSETS: return "IfcMaterialProfileWithOffsets";
case schema::IFCMATERIALUSAGEDEFINITION: return "IfcMaterialUsageDefinition";
case schema::IFCPRESENTATIONITEM: return "IfcPresentationItem";
case schema::IFCPROJECTEDCRS: return "IfcProjectedCRS";
case schema::IFCPROPERTYABSTRACTION: return "IfcPropertyAbstraction";
case schema::IFCRECURRENCEPATTERN: return "IfcRecurrencePattern";
case schema::IFCREFERENCE: return "IfcReference";
case schema::IFCRESOURCELEVELRELATIONSHIP: return "IfcResourceLevelRelationship";
case schema::IFCSCHEDULINGTIME: return "IfcSchedulingTime";
case schema::IFCSTRUCTURALLOADCONFIGURATION: return "IfcStructuralLoadConfiguration";
case schema::IFCSTRUCTURALLOADORRESULT: return "IfcStructuralLoadOrResult";
case schema::IFCSURFACEREINFORCEMENTAREA: return "IfcSurfaceReinforcementArea";
case schema::IFCTABLECOLUMN: return "IfcTableColumn";
case schema::IFCTASKTIME: return "IfcTaskTime";
case schema::IFCTASKTIMERECURRING: return "IfcTaskTimeRecurring";
case schema::IFCTEXTUREVERTEXLIST: return "IfcTextureVertexList";
case schema::IFCTIMEPERIOD: return "IfcTimePeriod";
case schema::IFCWORKTIME: return "IfcWorkTime";
case schema::IFCCOLOURRGBLIST: return "IfcColourRgbList";
case schema::IFCCONVERSIONBASEDUNITWITHOFFSET: return "IfcConversionBasedUnitWithOffset";
case schema::IFCEVENTTIME: return "IfcEventTime";
case schema::IFCEXTENDEDPROPERTIES: return "IfcExtendedProperties";
case schema::IFCEXTERNALREFERENCERELATIONSHIP: return "IfcExternalReferenceRelationship";
case schema::IFCINDEXEDCOLOURMAP: return "IfcIndexedColourMap";
case schema::IFCINDEXEDTEXTUREMAP: return "IfcIndexedTextureMap";
case schema::IFCINDEXEDTRIANGLETEXTUREMAP: return "IfcIndexedTriangleTextureMap";
case schema::IFCLAGTIME: return "IfcLagTime";
case schema::IFCMATERIALCONSTITUENT: return "IfcMaterialConstituent";
case schema::IFCMATERIALCONSTITUENTSET: return "IfcMaterialConstituentSet";
case schema::IFCMATERIALPROFILESETUSAGE: return "IfcMaterialProfileSetUsage";
case schema::IFCMATERIALPROFILESETUSAGETAPERING: return "IfcMaterialProfileSetUsageTapering";
case schema::IFCMATERIALRELATIONSHIP: return "IfcMaterialRelationship";
case schema::IFCMIRROREDPROFILEDEF: return "IfcMirroredProfileDef";
case schema::IFCPREDEFINEDPROPERTIES: return "IfcPreDefinedProperties";
case schema::IFCPROPERTYTEMPLATEDEFINITION: return "IfcPropertyTemplateDefinition";
case schema::IFCQUANTITYSET: return "IfcQuantitySet";
case schema::IFCRESOURCEAPPROVALRELATIONSHIP: return "IfcResourceApprovalRelationship";
case schema::IFCRESOURCECONSTRAINTRELATIONSHIP: return "IfcResourceConstraintRelationship";
case schema::IFCRESOURCETIME: return "IfcResourceTime";
case schema::IFCSWEPTDISKSOLIDPOLYGONAL: return "IfcSweptDiskSolidPolygonal";
case schema::IFCTESSELLATEDITEM: return "IfcTessellatedItem";
case schema::IFCTYPEPROCESS: return "IfcTypeProcess";
case schema::IFCTYPERESOURCE: return "IfcTypeResource";
case schema::IFCADVANCEDFACE: return "IfcAdvancedFace";
case schema::IFCCARTESIANPOINTLIST: return "IfcCartesianPointList";
case schema::IFCCARTESIANPOINTLIST2D: return "IfcCartesianPointList2D";
case schema::IFCCARTESIANPOINTLIST3D: return "IfcCartesianPointList3D";
case schema::IFCCONSTRUCTIONRESOURCETYPE: return "IfcConstructionResourceType";
case schema::IFCCONTEXT: return "IfcContext";
case schema::IFCCREWRESOURCETYPE: return "IfcCrewResourceType";
case schema::IFCCURVEBOUNDEDSURFACE: return "IfcCurveBoundedSurface";
case schema::IFCEVENTTYPE: return "IfcEventType";
case schema::IFCEXTRUDEDAREASOLIDTAPERED: return "IfcExtrudedAreaSolidTapered";
case schema::IFCFIXEDREFERENCESWEPTAREASOLID: return "IfcFixedReferenceSweptAreaSolid";
case schema::IFCGEOGRAPHICELEMENTTYPE: return "IfcGeographicElementType";
case schema::IFCINDEXEDPOLYGONALFACE: return "IfcIndexedPolygonalFace";
case schema::IFCINDEXEDPOLYGONALFACEWITHVOIDS: return "IfcIndexedPolygonalFaceWithVoids";
case schema::IFCLABORRESOURCETYPE: return "IfcLaborResourceType";
case schema::IFCPCURVE: return "IfcPcurve";
case schema::IFCPREDEFINEDPROPERTYSET: return "IfcPreDefinedPropertySet";
case schema::IFCPROCEDURETYPE: return "IfcProcedureType";
case schema::IFCPROJECTLIBRARY: return "IfcProjectLibrary";
case schema::IFCPROPERTYSETTEMPLATE: return "IfcPropertySetTemplate";
case schema::IFCPROPERTYTEMPLATE: return "IfcPropertyTemplate";
case schema::IFCRELASSIGNSTOGROUPBYFACTOR: return "IfcRelAssignsToGroupByFactor";
case schema::IFCRELDECLARES: return "IfcRelDeclares";
case schema::IFCRELDEFINESBYOBJECT: return "IfcRelDefinesByObject";
case schema::IFCRELDEFINESBYTEMPLATE: return "IfcRelDefinesByTemplate";
case schema::IFCRELINTERFERESELEMENTS: return "IfcRelInterferesElements";
case schema::IFCRELSPACEBOUNDARY1STLEVEL: return "IfcRelSpaceBoundary1stLevel";
case schema::IFCRELSPACEBOUNDARY2NDLEVEL: return "IfcRelSpaceBoundary2ndLevel";
case schema::IFCREPARAMETRISEDCOMPOSITECURVESEGMENT: return "IfcReparametrisedCompositeCurveSegment";
case schema::IFCREVOLVEDAREASOLIDTAPERED: return "IfcRevolvedAreaSolidTapered";
case schema::IFCSIMPLEPROPERTYTEMPLATE: return "IfcSimplePropertyTemplate";
case schema::IFCSPATIALELEMENT: return "IfcSpatialElement";
case schema::IFCSPATIALELEMENTTYPE: return "IfcSpatialElementType";
case schema::IFCSPATIALZONE: return "IfcSpatialZone";
case schema::IFCSPATIALZONETYPE: return "IfcSpatialZoneType";
case schema::IFCSPHERICALSURFACE: return "IfcSphericalSurface";
case schema::IFCSTRUCTURALSURFACEREACTION: return "IfcStructuralSurfaceReaction";
case schema::IFCSUBCONTRACTRESOURCETYPE: return "IfcSubContractResourceType";
case schema::IFCSURFACECURVE: return "IfcSurfaceCurve";
case schema::IFCTASKTYPE: return "IfcTaskType";
case schema::IFCTESSELLATEDFACESET: return "IfcTessellatedFaceSet";
case schema::IFCTOROIDALSURFACE: return "IfcToroidalSurface";
case schema::IFCTRIANGULATEDFACESET: return "IfcTriangulatedFaceSet";
case schema::IFCADVANCEDBREP: return "IfcAdvancedBrep";
case schema::IFCADVANCEDBREPWITHVOIDS: return "IfcAdvancedBrepWithVoids";
case schema::IFCBSPLINESURFACE: return "IfcBSplineSurface";
case schema::IFCBSPLINESURFACEWITHKNOTS: return "IfcBSplineSurfaceWithKnots";
case schema::IFCCHIMNEYTYPE: return "IfcChimneyType";
case schema::IFCCIVILELEMENTTYPE: return "IfcCivilElementType";
case schema::IFCCOMPLEXPROPERTYTEMPLATE: return "IfcComplexPropertyTemplate";
case schema::IFCCOMPOSITECURVEONSURFACE: return "IfcCompositeCurveOnSurface";
case schema::IFCCONSTRUCTIONEQUIPMENTRESOURCETYPE: return "IfcConstructionEquipmentResourceType";
case schema::IFCCONSTRUCTIONMATERIALRESOURCETYPE: return "IfcConstructionMaterialResourceType";
case schema::IFCCONSTRUCTIONPRODUCTRESOURCETYPE: return "IfcConstructionProductResourceType";
case schema::IFCCYLINDRICALSURFACE: return "IfcCylindricalSurface";
case schema::IFCDOORTYPE: return "IfcDoorType";
case schema::IFCELEMENTASSEMBLYTYPE: return "IfcElementAssemblyType";
case schema::IFCENGINETYPE: return "IfcEngineType";
case schema::IFCEVENT: return "IfcEvent";
case schema::IFCEXTERNALSPATIALSTRUCTUREELEMENT: return "IfcExternalSpatialStructureElement";
case schema::IFCFOOTINGTYPE: return "IfcFootingType";
case schema::IFCFURNITURE: return "IfcFurniture";
case schema::IFCGEOGRAPHICELEMENT: return "IfcGeographicElement";
case schema::IFCINDEXEDPOLYCURVE: return "IfcIndexedPolyCurve";
case schema::IFCINTERCEPTORTYPE: return "IfcInterceptorType";
case schema::IFCINTERSECTIONCURVE: return "IfcIntersectionCurve";
case schema::IFCMEDICALDEVICETYPE: return "IfcMedicalDeviceType";
case schema::IFCOPENINGSTANDARDCASE: return "IfcOpeningStandardCase";
case schema::IFCPILETYPE: return "IfcPileType";
case schema::IFCPOLYGONALFACESET: return "IfcPolygonalFaceSet";
case schema::IFCRAMPTYPE: return "IfcRampType";
case schema::IFCRATIONALBSPLINESURFACEWITHKNOTS: return "IfcRationalBSplineSurfaceWithKnots";
case schema::IFCREINFORCINGELEMENTTYPE: return "IfcReinforcingElementType";
case schema::IFCREINFORCINGMESHTYPE: return "IfcReinforcingMeshType";
case schema::IFCROOFTYPE: return "IfcRoofType";
case schema::IFCSEAMCURVE: return "IfcSeamCurve";
case schema::IFCSHADINGDEVICETYPE: return "IfcShadingDeviceType";
case schema::IFCSOLARDEVICETYPE: return "IfcSolarDeviceType";
case schema::IFCSTAIRTYPE: return "IfcStairType";
case schema::IFCSTRUCTURALCURVEACTION: return "IfcStructuralCurveAction";
case schema::IFCSTRUCTURALCURVEREACTION: return "IfcStructuralCurveReaction";
case schema::IFCSTRUCTURALSURFACEACTION: return "IfcStructuralSurfaceAction";
case schema::IFCSURFACEFEATURE: return "IfcSurfaceFeature";
case schema::IFCSYSTEMFURNITUREELEMENT: return "IfcSystemFurnitureElement";
case schema::IFCTENDONANCHORTYPE: return "IfcTendonAnchorType";
case schema::IFCTENDONTYPE: return "IfcTendonType";
case schema::IFCVIBRATIONISOLATOR: return "IfcVibrationIsolator";
case schema::IFCVOIDINGFEATURE: return "IfcVoidingFeature";
case schema::IFCWINDOWTYPE: return "IfcWindowType";
case schema::IFCWORKCALENDAR: return "IfcWorkCalendar";
case schema::IFCAUDIOVISUALAPPLIANCETYPE: return "IfcAudioVisualApplianceType";
case schema::IFCBSPLINECURVEWITHKNOTS: return "IfcBSplineCurveWithKnots";
case schema::IFCBOUNDARYCURVE: return "IfcBoundaryCurve";
case schema::IFCBUILDINGELEMENTPARTTYPE: return "IfcBuildingElementPartType";
case schema::IFCBUILDINGSYSTEM: return "IfcBuildingSystem";
case schema::IFCBURNERTYPE: return "IfcBurnerType";
case schema::IFCCABLEFITTINGTYPE: return "IfcCableFittingType";
case schema::IFCCHIMNEY: return "IfcChimney";
case schema::IFCCIVILELEMENT: return "IfcCivilElement";
case schema::IFCCOLUMNSTANDARDCASE: return "IfcColumnStandardCase";
case schema::IFCCOMMUNICATIONSAPPLIANCETYPE: return "IfcCommunicationsApplianceType";
case schema::IFCDISTRIBUTIONSYSTEM: return "IfcDistributionSystem";
case schema::IFCDOORSTANDARDCASE: return "IfcDoorStandardCase";
case schema::IFCELECTRICDISTRIBUTIONBOARDTYPE: return "IfcElectricDistributionBoardType";
case schema::IFCENGINE: return "IfcEngine";
case schema::IFCEVAPORATIVECOOLER: return "IfcEvaporativeCooler";
case schema::IFCEVAPORATOR: return "IfcEvaporator";
case schema::IFCEXTERNALSPATIALELEMENT: return "IfcExternalSpatialElement";
case schema::IFCFLOWMETER: return "IfcFlowMeter";
case schema::IFCHEATEXCHANGER: return "IfcHeatExchanger";
case schema::IFCHUMIDIFIER: return "IfcHumidifier";
case schema::IFCINTERCEPTOR: return "IfcInterceptor";
case schema::IFCJUNCTIONBOX: return "IfcJunctionBox";
case schema::IFCLAMP: return "IfcLamp";
case schema::IFCLIGHTFIXTURE: return "IfcLightFixture";
case schema::IFCMEDICALDEVICE: return "IfcMedicalDevice";
case schema::IFCMEMBERSTANDARDCASE: return "IfcMemberStandardCase";
case schema::IFCMOTORCONNECTION: return "IfcMotorConnection";
case schema::IFCOUTERBOUNDARYCURVE: return "IfcOuterBoundaryCurve";
case schema::IFCOUTLET: return "IfcOutlet";
case schema::IFCPIPEFITTING: return "IfcPipeFitting";
case schema::IFCPIPESEGMENT: return "IfcPipeSegment";
case schema::IFCPLATESTANDARDCASE: return "IfcPlateStandardCase";
case schema::IFCPROTECTIVEDEVICE: return "IfcProtectiveDevice";
case schema::IFCPROTECTIVEDEVICETRIPPINGUNITTYPE: return "IfcProtectiveDeviceTrippingUnitType";
case schema::IFCPUMP: return "IfcPump";
case schema::IFCRATIONALBSPLINECURVEWITHKNOTS: return "IfcRationalBSplineCurveWithKnots";
case schema::IFCREINFORCINGBARTYPE: return "IfcReinforcingBarType";
case schema::IFCSANITARYTERMINAL: return "IfcSanitaryTerminal";
case schema::IFCSHADINGDEVICE: return "IfcShadingDevice";
case schema::IFCSLABELEMENTEDCASE: return "IfcSlabElementedCase";
case schema::IFCSLABSTANDARDCASE: return "IfcSlabStandardCase";
case schema::IFCSOLARDEVICE: return "IfcSolarDevice";
case schema::IFCSPACEHEATER: return "IfcSpaceHeater";
case schema::IFCSTACKTERMINAL: return "IfcStackTerminal";
case schema::IFCSTRUCTURALLOADCASE: return "IfcStructuralLoadCase";
case schema::IFCSWITCHINGDEVICE: return "IfcSwitchingDevice";
case schema::IFCTANK: return "IfcTank";
case schema::IFCTRANSFORMER: return "IfcTransformer";
case schema::IFCTUBEBUNDLE: return "IfcTubeBundle";
case schema::IFCUNITARYCONTROLELEMENTTYPE: return "IfcUnitaryControlElementType";
case schema::IFCUNITARYEQUIPMENT: return "IfcUnitaryEquipment";
case schema::IFCVALVE: return "IfcValve";
case schema::IFCWALLELEMENTEDCASE: return "IfcWallElementedCase";
case schema::IFCWASTETERMINAL: return "IfcWasteTerminal";
case schema::IFCWINDOWSTANDARDCASE: return "IfcWindowStandardCase";
case schema::IFCAIRTERMINAL: return "IfcAirTerminal";
case schema::IFCAIRTERMINALBOX: return "IfcAirTerminalBox";
case schema::IFCAIRTOAIRHEATRECOVERY: return "IfcAirToAirHeatRecovery";
case schema::IFCAUDIOVISUALAPPLIANCE: return "IfcAudioVisualAppliance";
case schema::IFCBEAMSTANDARDCASE: return "IfcBeamStandardCase";
case schema::IFCBOILER: return "IfcBoiler";
case schema::IFCBURNER: return "IfcBurner";
case schema::IFCCABLECARRIERFITTING: return "IfcCableCarrierFitting";
case schema::IFCCABLECARRIERSEGMENT: return "IfcCableCarrierSegment";
case schema::IFCCABLEFITTING: return "IfcCableFitting";
case schema::IFCCABLESEGMENT: return "IfcCableSegment";
case schema::IFCCHILLER: return "IfcChiller";
case schema::IFCCOIL: return "IfcCoil";
case schema::IFCCOMMUNICATIONSAPPLIANCE: return "IfcCommunicationsAppliance";
case schema::IFCCOMPRESSOR: return "IfcCompressor";
case schema::IFCCONDENSER: return "IfcCondenser";
case schema::IFCCOOLEDBEAM: return "IfcCooledBeam";
case schema::IFCCOOLINGTOWER: return "IfcCoolingTower";
case schema::IFCDAMPER: return "IfcDamper";
case schema::IFCDISTRIBUTIONCIRCUIT: return "IfcDistributionCircuit";
case schema::IFCDUCTFITTING: return "IfcDuctFitting";
case schema::IFCDUCTSEGMENT: return "IfcDuctSegment";
case schema::IFCDUCTSILENCER: return "IfcDuctSilencer";
case schema::IFCELECTRICAPPLIANCE: return "IfcElectricAppliance";
case schema::IFCELECTRICDISTRIBUTIONBOARD: return "IfcElectricDistributionBoard";
case schema::IFCELECTRICFLOWSTORAGEDEVICE: return "IfcElectricFlowStorageDevice";
case schema::IFCELECTRICGENERATOR: return "IfcElectricGenerator";
case schema::IFCELECTRICMOTOR: return "IfcElectricMotor";
case schema::IFCELECTRICTIMECONTROL: return "IfcElectricTimeControl";
case schema::IFCFAN: return "IfcFan";
case schema::IFCFILTER: return "IfcFilter";
case schema::IFCFIRESUPPRESSIONTERMINAL: return "IfcFireSuppressionTerminal";
case schema::IFCFLOWINSTRUMENT: return "IfcFlowInstrument";
case schema::IFCPROTECTIVEDEVICETRIPPINGUNIT: return "IfcProtectiveDeviceTrippingUnit";
case schema::IFCSENSOR: return "IfcSensor";
case schema::IFCUNITARYCONTROLELEMENT: return "IfcUnitaryControlElement";
case schema::IFCACTUATOR: return "IfcActuator";
case schema::IFCALARM: return "IfcAlarm";
case schema::IFCCONTROLLER: return "IfcController";
case schema::IFCALIGNMENTPARAMETERSEGMENT: return "IfcAlignmentParameterSegment";
case schema::IFCALIGNMENTVERTICALSEGMENT: return "IfcAlignmentVerticalSegment";
case schema::IFCQUANTITYNUMBER: return "IfcQuantityNumber";
case schema::IFCTEXTURECOORDINATEINDICES: return "IfcTextureCoordinateIndices";
case schema::IFCTEXTURECOORDINATEINDICESWITHVOIDS: return "IfcTextureCoordinateIndicesWithVoids";
case schema::IFCALIGNMENTCANTSEGMENT: return "IfcAlignmentCantSegment";
case schema::IFCALIGNMENTHORIZONTALSEGMENT: return "IfcAlignmentHorizontalSegment";
case schema::IFCLINEARPLACEMENT: return "IfcLinearPlacement";
case schema::IFCOPENCROSSPROFILEDEF: return "IfcOpenCrossProfileDef";
case schema::IFCPOINTBYDISTANCEEXPRESSION: return "IfcPointByDistanceExpression";
case schema::IFCSEGMENT: return "IfcSegment";
case schema::IFCAXIS2PLACEMENTLINEAR: return "IfcAxis2PlacementLinear";
case schema::IFCCURVESEGMENT: return "IfcCurveSegment";
case schema::IFCDIRECTRIXCURVESWEPTAREASOLID: return "IfcDirectrixCurveSweptAreaSolid";
case schema::IFCINDEXEDPOLYGONALTEXTUREMAP: return "IfcIndexedPolygonalTextureMap";
case schema::IFCOFFSETCURVE: return "IfcOffsetCurve";
case schema::IFCOFFSETCURVEBYDISTANCES: return "IfcOffsetCurveByDistances";
case schema::IFCPOLYNOMIALCURVE: return "IfcPolynomialCurve";
case schema::IFCRELASSOCIATESPROFILEDEF: return "IfcRelAssociatesProfileDef";
case schema::IFCRELPOSITIONS: return "IfcRelPositions";
case schema::IFCSECTIONEDSOLID: return "IfcSectionedSolid";
case schema::IFCSECTIONEDSOLIDHORIZONTAL: return "IfcSectionedSolidHorizontal";
case schema::IFCSECTIONEDSURFACE: return "IfcSectionedSurface";
case schema::IFCSPIRAL: return "IfcSpiral";
case schema::IFCTHIRDORDERPOLYNOMIALSPIRAL: return "IfcThirdOrderPolynomialSpiral";
case schema::IFCTRANSPORTATIONDEVICETYPE: return "IfcTransportationDeviceType";
case schema::IFCTRIANGULATEDIRREGULARNETWORK: return "IfcTriangulatedIrregularNetwork";
case schema::IFCVEHICLETYPE: return "IfcVehicleType";
case schema::IFCBUILTELEMENTTYPE: return "IfcBuiltElementType";
case schema::IFCCLOTHOID: return "IfcClothoid";
case schema::IFCCOSINESPIRAL: return "IfcCosineSpiral";
case schema::IFCCOURSETYPE: return "IfcCourseType";
case schema::IFCDEEPFOUNDATIONTYPE: return "IfcDeepFoundationType";
case schema::IFCDIRECTRIXDERIVEDREFERENCESWEPTAREASOLID: return "IfcDirectrixDerivedReferenceSweptAreaSolid";
case schema::IFCFACILITY: return "IfcFacility";
case schema::IFCFACILITYPART: return "IfcFacilityPart";
case schema::IFCFACILITYPARTCOMMON: return "IfcFacilityPartCommon";
case schema::IFCGEOTECHNICALELEMENT: return "IfcGeotechnicalElement";
case schema::IFCGEOTECHNICALSTRATUM: return "IfcGeotechnicalStratum";
case schema::IFCGRADIENTCURVE: return "IfcGradientCurve";
case schema::IFCIMPACTPROTECTIONDEVICE: return "IfcImpactProtectionDevice";
case schema::IFCIMPACTPROTECTIONDEVICETYPE: return "IfcImpactProtectionDeviceType";
case schema::IFCKERBTYPE: return "IfcKerbType";
case schema::IFCLINEARELEMENT: return "IfcLinearElement";
case schema::IFCLIQUIDTERMINALTYPE: return "IfcLiquidTerminalType";
case schema::IFCMARINEFACILITY: return "IfcMarineFacility";
case schema::IFCMARINEPART: return "IfcMarinePart";
case schema::IFCMOBILETELECOMMUNICATIONSAPPLIANCETYPE: return "IfcMobileTelecommunicationsApplianceType";
case schema::IFCMOORINGDEVICETYPE: return "IfcMooringDeviceType";
case schema::IFCNAVIGATIONELEMENTTYPE: return "IfcNavigationElementType";
case schema::IFCPAVEMENTTYPE: return "IfcPavementType";
case schema::IFCPOSITIONINGELEMENT: return "IfcPositioningElement";
case schema::IFCRAILTYPE: return "IfcRailType";
case schema::IFCRAILWAY: return "IfcRailway";
case schema::IFCRAILWAYPART: return "IfcRailwayPart";
case schema::IFCREFERENT: return "IfcReferent";
case schema::IFCRELADHERESTOELEMENT: return "IfcRelAdheresToElement";
case schema::IFCROAD: return "IfcRoad";
case schema::IFCROADPART: return "IfcRoadPart";
case schema::IFCSECONDORDERPOLYNOMIALSPIRAL: return "IfcSecondOrderPolynomialSpiral";
case schema::IFCSEGMENTEDREFERENCECURVE: return "IfcSegmentedReferenceCurve";
case schema::IFCSEVENTHORDERPOLYNOMIALSPIRAL: return "IfcSeventhOrderPolynomialSpiral";
case schema::IFCSIGN: return "IfcSign";
case schema::IFCSIGNTYPE: return "IfcSignType";
case schema::IFCSIGNALTYPE: return "IfcSignalType";
case schema::IFCSINESPIRAL: return "IfcSineSpiral";
case schema::IFCTENDONCONDUIT: return "IfcTendonConduit";
case schema::IFCTENDONCONDUITTYPE: return "IfcTendonConduitType";
case schema::IFCTRACKELEMENTTYPE: return "IfcTrackElementType";
case schema::IFCTRANSPORTATIONDEVICE: return "IfcTransportationDevice";
case schema::IFCVEHICLE: return "IfcVehicle";
case schema::IFCVIBRATIONDAMPER: return "IfcVibrationDamper";
case schema::IFCVIBRATIONDAMPERTYPE: return "IfcVibrationDamperType";
case schema::IFCALIGNMENTCANT: return "IfcAlignmentCant";
case schema::IFCALIGNMENTHORIZONTAL: return "IfcAlignmentHorizontal";
case schema::IFCALIGNMENTSEGMENT: return "IfcAlignmentSegment";
case schema::IFCALIGNMENTVERTICAL: return "IfcAlignmentVertical";
case schema::IFCBEARINGTYPE: return "IfcBearingType";
case schema::IFCBRIDGE: return "IfcBridge";
case schema::IFCBRIDGEPART: return "IfcBridgePart";
case schema::IFCBUILTELEMENT: return "IfcBuiltElement";
case schema::IFCBUILTSYSTEM: return "IfcBuiltSystem";
case schema::IFCCAISSONFOUNDATIONTYPE: return "IfcCaissonFoundationType";
case schema::IFCCONVEYORSEGMENTTYPE: return "IfcConveyorSegmentType";
case schema::IFCCOURSE: return "IfcCourse";
case schema::IFCDEEPFOUNDATION: return "IfcDeepFoundation";
case schema::IFCDISTRIBUTIONBOARDTYPE: return "IfcDistributionBoardType";
case schema::IFCEARTHWORKSCUT: return "IfcEarthworksCut";
case schema::IFCEARTHWORKSELEMENT: return "IfcEarthworksElement";
case schema::IFCEARTHWORKSFILL: return "IfcEarthworksFill";
case schema::IFCELECTRICFLOWTREATMENTDEVICETYPE: return "IfcElectricFlowTreatmentDeviceType";
case schema::IFCGEOTECHNICALASSEMBLY: return "IfcGeotechnicalAssembly";
case schema::IFCKERB: return "IfcKerb";
case schema::IFCLINEARPOSITIONINGELEMENT: return "IfcLinearPositioningElement";
case schema::IFCLIQUIDTERMINAL: return "IfcLiquidTerminal";
case schema::IFCMOBILETELECOMMUNICATIONSAPPLIANCE: return "IfcMobileTelecommunicationsAppliance";
case schema::IFCMOORINGDEVICE: return "IfcMooringDevice";
case schema::IFCNAVIGATIONELEMENT: return "IfcNavigationElement";
case schema::IFCPAVEMENT: return "IfcPavement";
case schema::IFCRAIL: return "IfcRail";
case schema::IFCREINFORCEDSOIL: return "IfcReinforcedSoil";
case schema::IFCSIGNAL: return "IfcSignal";
case schema::IFCTRACKELEMENT: return "IfcTrackElement";
case schema::IFCALIGNMENT: return "IfcAlignment";
case schema::IFCBEARING: return "IfcBearing";
case schema::IFCBOREHOLE: return "IfcBorehole";
case schema::IFCCAISSONFOUNDATION: return "IfcCaissonFoundation";
case schema::IFCCONVEYORSEGMENT: return "IfcConveyorSegment";
case schema::IFCDISTRIBUTIONBOARD: return "IfcDistributionBoard";
case schema::IFCELECTRICFLOWTREATMENTDEVICE: return "IfcElectricFlowTreatmentDevice";
case schema::IFCGEOMODEL: return "IfcGeomodel";
case schema::IFCGEOSLICE: return "IfcGeoslice";
case schema::IFCABSORBEDDOSEMEASURE: return "IfcAbsorbedDoseMeasure";
case schema::IFCACCELERATIONMEASURE: return "IfcAccelerationMeasure";
case schema::IFCAMOUNTOFSUBSTANCEMEASURE: return "IfcAmountOfSubstanceMeasure";
case schema::IFCANGULARVELOCITYMEASURE: return "IfcAngularVelocityMeasure";
case schema::IFCAREAMEASURE: return "IfcAreaMeasure";
case schema::IFCBOOLEAN: return "IfcBoolean";
case schema::IFCBOXALIGNMENT: return "IfcBoxAlignment";
case schema::IFCCOMPLEXNUMBER: return "IfcComplexNumber";
case schema::IFCCOMPOUNDPLANEANGLEMEASURE: return "IfcCompoundPlaneAngleMeasure";
case schema::IFCCONTEXTDEPENDENTMEASURE: return "IfcContextDependentMeasure";
case schema::IFCCOUNTMEASURE: return "IfcCountMeasure";
case schema::IFCCURVATUREMEASURE: return "IfcCurvatureMeasure";
case schema::IFCDAYINMONTHNUMBER: return "IfcDayInMonthNumber";
case schema::IFCDAYLIGHTSAVINGHOUR: return "IfcDaylightSavingHour";
case schema::IFCDESCRIPTIVEMEASURE: return "IfcDescriptiveMeasure";
case schema::IFCDIMENSIONCOUNT: return "IfcDimensionCount";
case schema::IFCDOSEEQUIVALENTMEASURE: return "IfcDoseEquivalentMeasure";
case schema::IFCDYNAMICVISCOSITYMEASURE: return "IfcDynamicViscosityMeasure";
case schema::IFCELECTRICCAPACITANCEMEASURE: return "IfcElectricCapacitanceMeasure";
case schema::IFCELECTRICCHARGEMEASURE: return "IfcElectricChargeMeasure";
case schema::IFCELECTRICCONDUCTANCEMEASURE: return "IfcElectricConductanceMeasure";
case schema::IFCELECTRICCURRENTMEASURE: return "IfcElectricCurrentMeasure";
case schema::IFCELECTRICRESISTANCEMEASURE: return "IfcElectricResistanceMeasure";
case schema::IFCELECTRICVOLTAGEMEASURE: return "IfcElectricVoltageMeasure";
case schema::IFCENERGYMEASURE: return "IfcEnergyMeasure";
case schema::IFCFONTSTYLE: return "IfcFontStyle";
case schema::IFCFONTVARIANT: return "IfcFontVariant";
case schema::IFCFONTWEIGHT: return "IfcFontWeight";
case schema::IFCFORCEMEASURE: return "IfcForceMeasure";
case schema::IFCFREQUENCYMEASURE: return "IfcFrequencyMeasure";
case schema::IFCGLOBALLYUNIQUEID: return "IfcGloballyUniqueId";
case schema::IFCHEATFLUXDENSITYMEASURE: return "IfcHeatFluxDensityMeasure";
case schema::IFCHEATINGVALUEMEASURE: return "IfcHeatingValueMeasure";
case schema::IFCHOURINDAY: return "IfcHourInDay";
case schema::IFCIDENTIFIER: return "IfcIdentifier";
case schema::IFCILLUMINANCEMEASURE: return "IfcIlluminanceMeasure";
case schema::IFCINDUCTANCEMEASURE: return "IfcInductanceMeasure";
case schema::IFCINTEGER: return "IfcInteger";
case schema::IFCINTEGERCOUNTRATEMEASURE: return "IfcIntegerCountRateMeasure";
case schema::IFCIONCONCENTRATIONMEASURE: return "IfcIonConcentrationMeasure";
case schema::IFCISOTHERMALMOISTURECAPACITYMEASURE: return "IfcIsothermalMoistureCapacityMeasure";
case schema::IFCKINEMATICVISCOSITYMEASURE: return "IfcKinematicViscosityMeasure";
case schema::IFCLABEL: return "IfcLabel";
case schema::IFCLENGTHMEASURE: return "IfcLengthMeasure";
case schema::IFCLINEARFORCEMEASURE: return "IfcLinearForceMeasure";
case schema::IFCLINEARMOMENTMEASURE: return "IfcLinearMomentMeasure";
case schema::IFCLINEARSTIFFNESSMEASURE: return "IfcLinearStiffnessMeasure";
case schema::IFCLINEARVELOCITYMEASURE: return "IfcLinearVelocityMeasure";
case schema::IFCLOGICAL: return "IfcLogical";
case schema::IFCLUMINOUSFLUXMEASURE: return "IfcLuminousFluxMeasure";
case schema::IFCLUMINOUSINTENSITYDISTRIBUTIONMEASURE: return "IfcLuminousIntensityDistributionMeasure";
case schema::IFCLUMINOUSINTENSITYMEASURE: return "IfcLuminousIntensityMeasure";
case schema::IFCMAGNETICFLUXDENSITYMEASURE: return "IfcMagneticFluxDensityMeasure";
case schema::IFCMAGNETICFLUXMEASURE: return "IfcMagneticFluxMeasure";
case schema::IFCMASSDENSITYMEASURE: return "IfcMassDensityMeasure";
case schema::IFCMASSFLOWRATEMEASURE: return "IfcMassFlowRateMeasure";
case schema::IFCMASSMEASURE: return "IfcMassMeasure";
case schema::IFCMASSPERLENGTHMEASURE: return "IfcMassPerLengthMeasure";
case schema::IFCMINUTEINHOUR: return "IfcMinuteInHour";
case schema::IFCMODULUSOFELASTICITYMEASURE: return "IfcModulusOfElasticityMeasure";
case schema::IFCMODULUSOFLINEARSUBGRADEREACTIONMEASURE: return "IfcModulusOfLinearSubgradeReactionMeasure";
case schema::IFCMODULUSOFROTATIONALSUBGRADEREACTIONMEASURE: return "IfcModulusOfRotationalSubgradeReactionMeasure";
case schema::IFCMODULUSOFSUBGRADEREACTIONMEASURE: return "IfcModulusOfSubgradeReactionMeasure";
case schema::IFCMOISTUREDIFFUSIVITYMEASURE: return "IfcMoistureDiffusivityMeasure";
case schema::IFCMOLECULARWEIGHTMEASURE: return "IfcMolecularWeightMeasure";
case schema::IFCMOMENTOFINERTIAMEASURE: return "IfcMomentOfInertiaMeasure";
case schema::IFCMONETARYMEASURE: return "IfcMonetaryMeasure";
case schema::IFCMONTHINYEARNUMBER: return "IfcMonthInYearNumber";
case schema::IFCNORMALISEDRATIOMEASURE: return "IfcNormalisedRatioMeasure";
case schema::IFCNUMERICMEASURE: return "IfcNumericMeasure";
case schema::IFCPHMEASURE: return "IfcPHMeasure";
case schema::IFCPARAMETERVALUE: return "IfcParameterValue";
case schema::IFCPLANARFORCEMEASURE: return "IfcPlanarForceMeasure";
case schema::IFCPLANEANGLEMEASURE: return "IfcPlaneAngleMeasure";
case schema::IFCPOSITIVELENGTHMEASURE: return "IfcPositiveLengthMeasure";
case schema::IFCPOSITIVEPLANEANGLEMEASURE: return "IfcPositivePlaneAngleMeasure";
case schema::IFCPOSITIVERATIOMEASURE: return "IfcPositiveRatioMeasure";
case schema::IFCPOWERMEASURE: return "IfcPowerMeasure";
case schema::IFCPRESENTABLETEXT: return "IfcPresentableText";
case schema::IFCPRESSUREMEASURE: return "IfcPressureMeasure";
case schema::IFCRADIOACTIVITYMEASURE: return "IfcRadioActivityMeasure";
case schema::IFCRATIOMEASURE: return "IfcRatioMeasure";
case schema::IFCREAL: return "IfcReal";
case schema::IFCROTATIONALFREQUENCYMEASURE: return "IfcRotationalFrequencyMeasure";
case schema::IFCROTATIONALMASSMEASURE: return "IfcRotationalMassMeasure";
case schema::IFCROTATIONALSTIFFNESSMEASURE: return "IfcRotationalStiffnessMeasure";
case schema::IFCSECONDINMINUTE: return "IfcSecondInMinute";
case schema::IFCSECTIONMODULUSMEASURE: return "IfcSectionModulusMeasure";
case schema::IFCSECTIONALAREAINTEGRALMEASURE: return "IfcSectionalAreaIntegralMeasure";
case schema::IFCSHEARMODULUSMEASURE: return "IfcShearModulusMeasure";
case schema::IFCSOLIDANGLEMEASURE: return "IfcSolidAngleMeasure";
case schema::IFCSOUNDPOWERMEASURE: return "IfcSoundPowerMeasure";
case schema::IFCSOUNDPRESSUREMEASURE: return "IfcSoundPressureMeasure";
case schema::IFCSPECIFICHEATCAPACITYMEASURE: return "IfcSpecificHeatCapacityMeasure";
case schema::IFCSPECULAREXPONENT: return "IfcSpecularExponent";
case schema::IFCSPECULARROUGHNESS: return "IfcSpecularRoughness";
case schema::IFCTEMPERATUREGRADIENTMEASURE: return "IfcTemperatureGradientMeasure";
case schema::IFCTEXT: return "IfcText";
case schema::IFCTEXTALIGNMENT: return "IfcTextAlignment";
case schema::IFCTEXTDECORATION: return "IfcTextDecoration";
case schema::IFCTEXTFONTNAME: return "IfcTextFontName";
case schema::IFCTEXTTRANSFORMATION: return "IfcTextTransformation";
case schema::IFCTHERMALADMITTANCEMEASURE: return "IfcThermalAdmittanceMeasure";
case schema::IFCTHERMALCONDUCTIVITYMEASURE: return "IfcThermalConductivityMeasure";
case schema::IFCTHERMALEXPANSIONCOEFFICIENTMEASURE: return "IfcThermalExpansionCoefficientMeasure";
case schema::IFCTHERMALRESISTANCEMEASURE: return "IfcThermalResistanceMeasure";
case schema::IFCTHERMALTRANSMITTANCEMEASURE: return "IfcThermalTransmittanceMeasure";
case schema::IFCTHERMODYNAMICTEMPERATUREMEASURE: return "IfcThermodynamicTemperatureMeasure";
case schema::IFCTIMEMEASURE: return "IfcTimeMeasure";
case schema::IFCTIMESTAMP: return "IfcTimeStamp";
case schema::IFCTORQUEMEASURE: return "IfcTorqueMeasure";
case schema::IFCVAPORPERMEABILITYMEASURE: return "IfcVaporPermeabilityMeasure";
case schema::IFCVOLUMEMEASURE: return "IfcVolumeMeasure";
case schema::IFCVOLUMETRICFLOWRATEMEASURE: return "IfcVolumetricFlowRateMeasure";
case schema::IFCWARPINGCONSTANTMEASURE: return "IfcWarpingConstantMeasure";
case schema::IFCWARPINGMOMENTMEASURE: return "IfcWarpingMomentMeasure";
case schema::IFCYEARNUMBER: return "IfcYearNumber";
case schema::IFCARCINDEX: return "IfcArcIndex";
case schema::IFCAREADENSITYMEASURE: return "IfcAreaDensityMeasure";
case schema::IFCBINARY: return "IfcBinary";
case schema::IFCCARDINALPOINTREFERENCE: return "IfcCardinalPointReference";
case schema::IFCDATE: return "IfcDate";
case schema::IFCDATETIME: return "IfcDateTime";
case schema::IFCDAYINWEEKNUMBER: return "IfcDayInWeekNumber";
case schema::IFCDURATION: return "IfcDuration";
case schema::IFCLANGUAGEID: return "IfcLanguageId";
case schema::IFCLINEINDEX: return "IfcLineIndex";
case schema::IFCNONNEGATIVELENGTHMEASURE: return "IfcNonNegativeLengthMeasure";
case schema::IFCPOSITIVEINTEGER: return "IfcPositiveInteger";
case schema::IFCPROPERTYSETDEFINITIONSET: return "IfcPropertySetDefinitionSet";
case schema::IFCSOUNDPOWERLEVELMEASURE: return "IfcSoundPowerLevelMeasure";
case schema::IFCSOUNDPRESSURELEVELMEASURE: return "IfcSoundPressureLevelMeasure";
case schema::IFCTEMPERATURERATEOFCHANGEMEASURE: return "IfcTemperatureRateOfChangeMeasure";
case schema::IFCTIME: return "IfcTime";
case schema::IFCURIREFERENCE: return "IfcURIReference";
default: return "<web-ifc-type-unknown>";
}
}
}